### ISSUE TITLE
Header appendgrid doesn't work properly

### ISSUE THREAD

**Issue by Ridwan09** [hkalbertl/jquery.appendGrid#100]
@hkalbertl Why header appendgrid doesn't appropriate with body? the problem occurs when column type is hidden 
![github](https://cloud.githubusercontent.com/assets/17821729/23261542/43e179e8-fa09-11e6-989e-e8f81fa0e628.PNG)

**Comment by hkalbertl** [comment]
Hi Ridwan09,

It looks like the cell width is not calculated correctly.
Or some extra style / CSS class are applied / inherited to the grid?

Can you provide a jsFiddle or source code for this issue? Thanks!

**Comment by Ridwan09** [comment]
this link https://jsfiddle.net/ridwan09/d3d88qdp/ for jsFiddle  on my issue thanks!

**Comment by hkalbertl** [comment]
Hi Ridwan09,

It looks like there is a bug on calculating column width when the command buttons at the end of rows are not visible. I will publish a new version of `appendGrid` to fix this problem very soon. Thanks!

**Comment by hkalbertl** [comment]
I just published v1.6.3 that fixed this problem.
And I tried it in your jsFiddle which is working fine.
Thanks for using `appendGrid`!

**Comment by Ridwan09** [comment]
oke thank you so much for your attention!
