### ISSUE TITLE
color picker inside appendGrid

### ISSUE THREAD

**Issue by karthiksd9** [hkalbertl/jquery.appendGrid#102]
Is it possible to add a color picker inside appendGrid column?
If possible can you please show the code snippet of the same?

Thanks in advance :)

**Comment by karthiksd9** [comment]
Well. I just saw there is a column type called 'color'.
That should work for me.

It would be great if you add jquery-UI colorpicker type. Just like datepicker.

**Comment by hkalbertl** [comment]
Hi karthiksd9,

Yes. You can use color as the type of column. `appendGrid` will generate the default color input as provided by your web browser. You may take a look on the following example:

```javascript
$('#tblAppendGrid').appendGrid({
    columns: [{
      name: 'name',
      display: 'Name'
    }, {
      name: 'color',
      display: 'Color',
      type: 'color'
    }]
  });
```

I guess you are talking about the color picker in jQuery UI ThemeRoller. I am afraid it is not an UI Widget and I cannot find out the binary for it.

I believe there are several color picker plugin on Internet. You may choose one of them and make use of [CustomType](https://appendgrid.apphb.com/Demo/CustomType) to generate color input in your grid. Hope it can help. Thanks!

**Comment by karthiksd9** [comment]
Thanks @hkalbertl . That's very helpful :)
