### ISSUE TITLE
Help me!!!

### ISSUE THREAD

**Issue by ObjectXhy** [hkalbertl/jquery.appendGrid#104]
If I want to click on the "append" code automatically generated, and how to do?

**Comment by hkalbertl** [comment]
Hi ObjectXhy,

Sorry that I don't understand your question.
Can you describe in more detail and/or with an example?

**Comment by ObjectXhy** [comment]
![qq 20170605141829](https://user-images.githubusercontent.com/22343268/26909778-a83af2e2-4c35-11e7-8d6d-542d0b5d5e71.jpg)
Sorry!
My English is very bad!
When I click on add a line trigger an event, because I want to achieve one of the fields automatically generated code.
Can you understand?
In addition, the control input is not support onDoubleClick event?
Best wish for you!

**Comment by hkalbertl** [comment]
Hi ObjectXhy,

May be you can take a look on [afterRowAppended](https://appendgrid.apphb.com/Documentation#link-afterRowAppended) and [afterRowInserted](https://appendgrid.apphb.com/Documentation#link-afterRowInserted) events. For example:

```javascript
$('#tblAppendGrid').appendGrid({
  columns: [/*Your columns definitions*/],
  afterRowAppended: function(caller, parentRowIndex, addedRowIndex) {
    for (var z = 0; z < addedRowIndex.length; z++) {
      var generatedCode = generateYourCodeHere();
      $(caller).appendGrid('setCtrlValue', 'CodeColumnName', addedRowIndex[z], generatedCode);
    }
  },
  afterRowInserted: function(caller, parentRowIndex, addedRowIndex) {
    // Should be something similar to above event
  }
});
```

For your second question, you can add double click event by using jQuery [on](http://api.jquery.com/on/) event handler. For example: 

```javascript
$(function(){
  // Initialize your grid first
  $('#tblAppendGrid').appendGrid(/*Your grid initialize parameters*/);
  // Add double event for all textbox,
  // you can modify the second parameter which is the jQuery selector to fit your need
  $('#tblAppendGrid').on('dblclick', 'input[type=text]', function(e) {
    var callerId = $(this).attr('id');
    var pattern = callerId.split('_');
    var uniqueIndex = pattern[pattern.length - 1];
    var columnName = pattern[pattern.length - 2];
    // Handle your double click event here
  });
});
```
