### ISSUE TITLE
HTML5 range ctrl

### ISSUE THREAD

**Issue by nmisdev** [hkalbertl/jquery.appendGrid#105]
How do I assign a value to this ?

name: 'span', display: 'DimmerRange', type: 'range', value: '90' 

The range is generated OK, but does not follow the value assigned

**Comment by hkalbertl** [comment]
Hi nmisdev,

I checked that the range type column is working properly.
May be you can take a look on my [HTML5 Demo](https://appendgrid.apphb.com/Demo/Html5).

If you still have problem, please let me know the web browser that you are using and detailed sample code / jsfiddle. Thanks!

**Comment by nmisdev** [comment]
All fixed thanks - I had missed the min/max values

Regards
