### ISSUE TITLE
Regarding pagination

### ISSUE THREAD

**Issue by saikumar100** [hkalbertl/jquery.appendGrid#108]
Hi,
   I have a jsp page where I will load around 100  or more rows in appendgrid. So, is there any way to add pagination in appendgrid.

Thanks,
Nick.

**Comment by hkalbertl** [comment]
Hi saikumar100,

Currently, appendGrid does not supported paging.
You may take a look on [fix header demo](https://appendgrid.apphb.com/Demo/FixHeader) if you don't want a long table on screen. Thanks!
