### ISSUE TITLE
Jquery files not found because no access to CDN

### ISSUE THREAD

**Issue by richb201** [hkalbertl/jquery.appendGrid#110]
My app runs as a chrome extension. To do this I need to upload it to the chrome server. Unfortunately, due to security constraints developers cannot access files that are on a CDN from a Chrome Extension. The way around this is upload every file that is needed to the Chrome Server (in the same directory as my files) itself. The problem is that there are a large number of files and I am afraid to start uploading if there is little chance of success. Is there a place where I can get the files needed to support the use of jquery and appendgrid that do not require access to a CDN?  see the errors I am getting below. 

Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.ui.base.css Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.ui.core.css Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.ui.accordion.css Failed to load resource: the server responded with a status of 404 (Not Found)
ui-bg_highlight-soft_75_cccccc_1x100.png Failed to load resource: the server responded with a status of 404 (Not Found)
ui-bg_glass_75_e6e6e6_1x400.png Failed to load resource: the server responded with a status of 404 (Not Found)
ui-bg_flat_75_ffffff_40x100.png Failed to load resource: the server responded with a status of 404 (Not Found)
ui-bg_glass_65_ffffff_1x400.png Failed to load resource: the server responded with a status of 404 (Not Found)
ui-icons_888888_256x240.png Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.ui.theme.css Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.ui.accordion.css Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.ui.base.css Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.ui.core.css Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by hkalbertl** [comment]
Hi richb201,

May be you can download a [custom build of jQuery UI](https://jqueryui.com/download/) that just contain required components as stated in [appendGrid github page](https://github.com/hkalbertl/jquery.appendGrid#prerequisite). I guess it should reduce the number of files in your whole package.

**Comment by richb201** [comment]
Hey Albert! I just  yesterday finished the backend for my system and
planned today to get back to appendGrid to attach the two!

Thank you, Rich
