### ISSUE TITLE
JQuery UI 1.12.1 

### ISSUE THREAD

**Issue by gdevilee** [hkalbertl/jquery.appendGrid#113]
appendGrid is not compatible with jQuery UI 1.12.1 (option: $.uiBackCompat = false;) 

Button icons has changed:

old
$( "button" ).button( {
    icons: {
        primary: "ui-icon-lock"
    }
} );

new

$( "button" ).button( {
    icon: "ui-icon-lock"
} );

change log JQuery UI 1.12.1:  http://jqueryui.com/upgrade-guide/1.12/#preparing-for-jquery-ui-1-13

**Comment by hkalbertl** [comment]
Thanks gdevilee,

I will take a look on that soon.
Probably `appendGrid` will drop support on jQuery UI v1.11.X and set v1.12 as minimum.

**Comment by hkalbertl** [comment]
Hi,

Please check `appendGrid` v1.7.0 which supports jQuery UI 1.12.
Thanks for using `appendGrid`!
