### ISSUE TITLE
Multiselect dropdown doesn't work properly.

### ISSUE THREAD

**Issue by shahab2058** [hkalbertl/jquery.appendGrid#114]
There is no method explained in the documentation to initialize the multiselect dropdown and how to successfully submit it. 
Please Help!

**Comment by hkalbertl** [comment]
Hi,

There is no "multiselect dropdown" supported in `appendGrid`.
But you can specify "multiple" in HTML select element to provide multiple selection.
For example:

```javascript
$('#tblAppendGrid').appendGrid({
  columns: [
    {
      name: 'fruit',
      type: 'select',
      ctrlOptions: {
        0: 'Apple',
        1: 'Banana',
        2: 'Cherry',
        3: 'Orange',
        4: 'Watermelon'
      },
      ctrlAttr: {
        multiple: 'multiple' // Enable multiple selection!
      }
    }
  ]
});
```

As "select" element is a generic HTML input, you should able to read the submitted values on server side (PHP/JSP/ASP/etc).

If you really want a true "multiselect dropdown" in `appendGrid`, you need to create your own by using [custom type](https://appendgrid.apphb.com/Demo/CustomType).

**Comment by shahab2058** [comment]
I have already tried this method but it has two basic issues:
It doesn't allow you to define name of the select element as array because it appends the unique number at the end which makes it something like example[]_123
It doesn't allow the method to pass list of already selected items while initializing the append grid. 

Can you share an example?

Thanks in Advance

**Comment by hkalbertl** [comment]
For your first issue about the name, I would say it is part of the design of this library. But you should able to read all the values by splitting `rowOrder` at server side. Here is the [ASP.NET](https://appendgrid.apphb.com/Demo/ServerHandling) sample for reading posted form data. Alternatively, you may use [getAllValue](https://appendgrid.apphb.com/Documentation#link-getAllValue) method to retrieve grid values as array (or object) and format the name of them before submit to server (may be by AJAX).

For your second issue about multiple selection on select element, it should be a bug that initial values cannot be passed in. I will prepare an update very soon.

**Comment by hkalbertl** [comment]
Hi,

Please check the v1.7.1 that fixed the problem on get/set multiple select element issue.
You may take a look on my [sample](https://jsfiddle.net/hkalbertl/bo5170uw/) as well. Thanks!
