### ISSUE TITLE
Disabled Input

### ISSUE THREAD

**Issue by tecomunico** [hkalbertl/jquery.appendGrid#116]
Good morning.
How set disable a text input field ?

**Comment by hkalbertl** [comment]
Hi,

If you want to set it disabled during grid initialization, you can make use of [ctrlProp](https://appendgrid.apphb.com/Documentation#link-ctrlProp) option. For example:

```javascript
$(function(){
  $('#tblAppendGrid').appendGrid({
    columns: [
      { name: 'MyTextbox', ctrlProp: { disabled: true } }
    ]
    ...
  });
});
```

If you want to disable it after initialization, you can get the input element by using [getCellCtrl](https://appendgrid.apphb.com/Documentation#link-getCellCtrl) first and then enable/disable it. For example:

```javascript
var textbox = $('#tblAppendGrid').appendGrid('getCellCtrl', 'MyTextbox', 1); // The last parameter is row number
$(textbox).prop('disabled', true);
```

Hope it can help :)

**Comment by tecomunico** [comment]
Thanks. Work perfect !!

2018-01-31 20:32 GMT-05:00 Albert L. <notifications@github.com>:

**Comment by tecomunico** [comment]
Another Question:  How do i put tag <tfoot>. i need add Total Column in the footer.
<tfoot>
     <tr>
	 <td>Sum</td>
	<td>$180</td>
    </tr>
</tfoot>

**Comment by hkalbertl** [comment]
I am afraid you need to modify the table HTML elements for that.
Assumed that you have 6 columns in the grid and the last column require a total.
In this case, td in the tfoot section will have colspan="8" which is (6 columns + first column + last column). You may take a look the following sample code to add the total.

```javascript
$(function(){
  $('#tblAppendGrid').appendGrid({
    // Add your init options
  });
  // Change the colspan of the existing footer cell
  var $footer = $('#tblAppendGrid tfoot tr');
  $footer.find('td').attr('colspan', 6);
  // Add the total cell and set the ID to tblAppendGrid_total
  $('<td></td>').attr('id', 'tblAppendGrid_total').css('text-align', 'right').appendTo($footer);
  // Add another cell for the last column
  $('<td></td>').appendTo($footer);
});
```

When the total required to update, you should able to change the content by something like:
```javascript
$('#tblAppendGrid_total').text(your_total_amount);
```
