### ISSUE TITLE
Bootstrap 4 Availability

### ISSUE THREAD

**Issue by cottonfieldusa** [hkalbertl/jquery.appendGrid#118]
Hi,
  Although its not ready, how can I down load Boostrap version of Append grid?
I am using the append grid at its basic form.
Q

**Comment by hkalbertl** [comment]
Hi cottonfieldusa,

As you know it is still under development, the final version may be complete different to current working version. You may take a look the Bootstrap 4 sample [here](https://appendgrid.apphb.com/Ver2) and use it by downloading the jquery.appendGrid-development-v2.js and jquery.appendGrid-development-v2.css. And sorry that I cannot provide support at this stage. Please come back and check the status later :)

**Comment by hkalbertl** [comment]
Hi cottonfieldusa,

The new version of AppendGrid that can work with Bootstrap 4 is out now!
You may check demo and docs on [AppendGrid website](https://appendgrid.apphb.com/).
And I planned to add more demo cases in future. I hope you’ll enjoy it!

**Comment by cottonfieldusa** [comment]
Thank you for working on version 2.
I have been using version 1 in the application and its been great!
Thanks..

I would like upgrade to version 2 (pure javascript with bulma) from version 1 and keep the same 
look of it from version 1 (Jquery UI default blue)

What is the best way to do this?

Q

**Comment by hkalbertl** [comment]
Hi cottonfieldusa,

There are several breaking changes in version 2 (such as removed jQuery as dependence) so I am afraid you need to change your code and test the grid one by one. I tried to keep the name of options and methods unchanged to help developers a bit easier to upgrade.

For example, if your grid is simple enough:
```javascript
// Version 1
$('#tblAppendGrid').appendGrid({
  columns: [/* Your columns */],
  initData: [/* Your data */]
});
```
You may just modify the first line and add element / uiFramework to make it work with Bulma:
```javascript
// Version 2
var myAppendGrid = new AppendGrid({
  element: "tblAppendGrid",
  uiFramework: "bulma",
  iconFramework: "fontawesome5", // Optional
  columns: [/* Your columns */],
  initData: [/* Your data */]
});
```

The event handling on generated input elements are changed quite a lot. Please check the [demo](https://appendgrid.apphb.com/Demo/Event) and [documentation](https://appendgrid.apphb.com/Documentation#link-events) for more. Thanks for using AppendGrid!
