### ISSUE TITLE
¿ it is possible to give responsive size ?

### ISSUE THREAD

**Issue by YulianD** [hkalbertl/jquery.appendGrid#121]
Hi cordial greeting, it is possible to **give a responsive size** to the table **appendGrid** .

> and thanks for your work, jquery.appendGrid is really very useful.

**Comment by hkalbertl** [comment]
Hi YulianD,

As current version of  `appendGrid` is based on jQuery UI which is not designed for responsive, I would say it is hard to give a responsive size to the table.

Actually, I am working on a new version of `appendGrid` which based on [Bootstrap 4](https://getbootstrap.com/). I can see it has a sample of [responsive table](https://getbootstrap.com/docs/4.1/content/tables/#responsive-tables) that may fit your need. I will reserve a room of this feature and try to put it into the new version of `appendGrid`!
