### ISSUE TITLE
Current status of v2

### ISSUE THREAD

**Issue by kkieslich** [hkalbertl/jquery.appendGrid#126]
Hi,
maybe I haven't looked carefully enough but I was wondering what the current state of the v2 is?
Appearently you are still working on v2 as you just made a commit but I could not find a lot of information about what actually works right now. I cloned your v2-branch but using that I could only add and remove rows. Any of the buttons on the rows (move up/down, remove,..) do not work. 
As we are using your Grid in our project and we want to remove the old jQueryUI your v2 would be awesome. Did I do something wrong or is it just not implemented yet? If not, do you have some kind of broad estimate when a "useable" version will be available?

Thanks in Advance

**Comment by hkalbertl** [comment]
Hi kkieslich,

I am still working on the v2 which it is not "useable" yet.
The insert / remove / move up / down buttons was not working in the previous commit.
You may try to update my code from v2-branch that resolved above buttons events.

Sorry that I cannot give an accurate release date of v2 but I wish to complete all basic features as below by early May 2019:
- Compatible with Bootstrap 4 / Bulma
- All buttons working
- Custom controls
- Able to serialize form values
- Add / move row programmatically
- An elegant way to handle column events

In the mean time, you may check my latest example here: [Bootstrap 4](https://appendgrid.apphb.com/Ver2) / [Bulma](https://appendgrid.apphb.com/Ver2/Bulma)

Thanks for using `appendGrid`!

**Comment by hkalbertl** [comment]
Hi kkieslich,

The new version of AppendGrid that can work with Bootstrap 4 is out now!
You may check demo and docs on [AppendGrid website](https://appendgrid.apphb.com/).
And I planned to add more demo cases in future. I hope you’ll enjoy it!

**Comment by kkieslich** [comment]
Thank you for your work, I'll try to migrate
