### ISSUE TITLE
Callbacks not working correctly

### ISSUE THREAD

**Issue by kkieslich** [hkalbertl/jquery.appendGrid#128]
Hi,
I tried to migrate from v1 to v2. The biggest part went very smooth, however I am having trouble with the callbacks. If i try to access a function e.g getUniqueIndex of the appendGrid-object inside a callback function i am getting the error that Cannot read property 'getUniqueIndex' of undefined. I even tried the example given in the documentation 
[AppendGrid Tests.zip](https://github.com/hkalbertl/jquery.appendGrid/files/3305646/AppendGrid.Tests.zip)
 and got the same error. Hope you can help me.

Thanks in Advance

**Comment by hkalbertl** [comment]
Hi kkieslich,

I just tested your code and got your "undefined" problem.
It would be a limitation that the code within "afterRowAppended" try to access "myAppendGrid" but it was not initialized.

As a workaround, you may check "myAppendGrid" is defined inside "afterRowAppended". For example:
```javascript
...
afterRowAppended: function(caller, parentRowIndex, addedRowIndex) {
  // Make sure AppendGrid is initialized
  if (myAppendGrid) {
    // Your code to copy values
    ...
  }
}
...
```

You may take a look on this pen as well.
https://codepen.io/hkalbertl/pen/qwzQQO

Hope it can help! :)

**Comment by kkieslich** [comment]
Hi,
yes that workaround worked perfectly. 
Thank you!
