### ISSUE TITLE
removeEmptyRows issue

### ISSUE THREAD

**Issue by malohtie** [hkalbertl/jquery.appendGrid#129]
Hi

first thanks for this amazing work ^^

about the removeEmptyRows option the documentation say 

**Remove all empty rows in grid. You may need to change the emptyCriteria to meet your requirement.**

i setup the emptyCriteria but it remove only one row per click you need to click twice to remove second row ...

you can see my exemple in fiddle 

https://jsfiddle.net/8f9za4up/

also it throw this error in my local dev
![image](https://user-images.githubusercontent.com/20033279/65365342-8d511700-dc10-11e9-910b-945bb84525b9.png)

**Comment by hkalbertl** [comment]
Hi malohtie,

I found that it was a problem on removing rows when `hideRowNumColumn` is being used.
Please update the reference to `AppendGrid` latest version in to your example and it should work without changing your coding. Thanks!

**Comment by malohtie** [comment]
Great, i'm waiting changes in jsdelivr 👍 

Thanks ^^
