### ISSUE TITLE
Support textarea 

### ISSUE THREAD

**Issue by jyeros** [hkalbertl/jquery.appendGrid#134]
Support `textarea` as column type

**Comment by hkalbertl** [comment]
Hi jyeros,

`textarea` is already supported.
Here is an example for generate `textarea` column:

```javascript
new AppendGrid({
  element: "tblAppendGrid",
  ...
  columns: [
    {
      name: "ta",
      display: "Text Area",
      // Required. Assign "textarea" as type
      type: "textarea",
      // Optional. Specify extra control attributes, such as number of rows
      ctrlAttr: {
        rows: 5
      }
    },
    ...
  ]
});
```

Hope it can help. Thanks!

**Comment by jyeros** [comment]
I tried now and works perfect, thanks a lot.

Sorry i didn't try it before because i didn't see it at [doc](https://appendgrid.apphb.com/Documentation#link-type)

**Comment by hkalbertl** [comment]
Oops...
I wasn't notice that `textarea` was missing in the doc.
The doc is now updated. Thanks!

**Comment by jyeros** [comment]
Thank you
