### ISSUE TITLE
select option dynamically on click

### ISSUE THREAD

**Issue by malohtie** [hkalbertl/jquery.appendGrid#135]
let say i have a button outside the grid and want to select the first option in all select available in appendGrid, cant find an option in the api is this possible ?
thanks

**Comment by hkalbertl** [comment]
Hi malohtie,

I guess the most straight forward way is to get the number of rows by [getRowCount](https://appendgrid.apphb.com/Documentation#link-getRowCount) first and then get the select DOM element by [getCellCtrl](https://appendgrid.apphb.com/Documentation#link-getCellCtrl) and change the `selectedIndex`of it. For example,
```javascript
// Initilize the grid
var myAppendGrid = new AppendGrid({ 
  columns:[
    {
      name: 'dropdown',
      type: 'select'
    }
  ]
});

// When your button clicked
$('#button').on('click', function(){
  var total = myAppendGrid.getRowCount();
  for (var z = 0; z < total; z++) {
    // Get the select element
    var select = myAppendGrid.getCellCtrl('dropdown', z);
    // Change the selected index
    select.selectedIndex = 0;
    // Optional: Trigger change event if required
    $(select).trigger('change');
  }
});
```
