### ISSUE TITLE
ctrlClass not added for checkbox type

### ISSUE THREAD

**Issue by malohtie** [hkalbertl/jquery.appendGrid#136]
Hi,

when adding a custom class for the checkbox input type it doesn't append is it the normal behaviour ? as the docs say it  will not be applied only  for `custom` type. 

```
{
      name: "isNPO",
      display: "NPO?",
      type: "checkbox",
      ctrlClass: "my-class"
},
```

https://codepen.io/malohtie/pen/NWrKpJw

![image](https://user-images.githubusercontent.com/20033279/95125516-030d1f80-074d-11eb-936d-14d8d0aaf081.png)

**Comment by hkalbertl** [comment]
Hi malohtie,

Yes, it is a bug on Bootstrap checkbox. There is an update version in master branch that fixed this issue.
I am testing on other cases now and publish it if there are no further problems. Thanks!
