### ISSUE TITLE
customFooterButtons

### ISSUE THREAD

**Issue by kkarika** [hkalbertl/jquery.appendGrid#139]
Hi Albert!

Great work!! I have used appendGrid a lot and I love it. Thank you for your hard work. 

Is there an example of customFooterButtons? I spent a lot of time looking for how to create customFooterButtons but I couldn't find it in the documentation I probably missed it. 
Could you please show me an example? That'll be really really helpful! 

So grateful for your time!!!

**Comment by hkalbertl** [comment]
Hi kkarika,

Do you mean you wish to add an extra button after the standard [+] [-] buttons?
There is no such setting for that but you may add a button directly the the grid table after `AppendGrid` initialized.
For example,

```javascript
// Initialize the grid
var myAppendGrid = new AppendGrid(...);

// Add an extra button
$('<button></button>').attr('type', 'button').addClass('btn btn-sm btn-success')
.text('My Extra button').appendTo('#tblAppendGrid tfoot tr td:first')
.on('click', function(){
  // Do something when the button is clicked
});
```
Hope it can help. Thanks for using `AppendGrid`!

**Comment by kkarika** [comment]
Yes! This is perfect! I did something like that as well. 

Thank you so much for your time!
