### ISSUE TITLE
Clear or RemoveAll Methods

### ISSUE THREAD

**Issue by marcoas** [hkalbertl/jquery.appendGrid#143]
(Translated by Google)

Hello

How can I clean or empty the grid?
Isn't there a method "clear" or "removeAll" or something similar?

Thank you

**Comment by hkalbertl** [comment]
Hi marcoas,

There is no "clear" or "removeAll" method available at this moment.

Alternatively, you may load an array with a single empty object to "simulate" clear all rows.
Please take a look this [pen](https://codepen.io/hkalbertl/pen/ZExNMPP) for more.

Hope it can help!
