### ISSUE TITLE
How can I create a grid with subgrid ? [question]

### ISSUE THREAD

**Issue by iannos** [hkalbertl/jquery.appendGrid#33]
A feature for grid-subgrid would be very useful. 
For example a table with customer names and each customer can have a table with addresses

Is that possible for now ?

**Comment by navdeepkaur12** [comment]
I don't want t have a sub panel for each and every row and just want it where the main row and has sub records. Is it possible to have sub panel for some rows only?

**Comment by hkalbertl** [comment]
Hi @navdeepkaur12,

I am afraid you need to generate sub panel for all rows.
But you may apply style on it to show or hide it. For example:

```javascript
$(function() {
    $('#tblAppendGrid').appendGrid({
        columns: [/* Standard columns */],
        useSubPanel: true, // Required
        subPanelBuilder: function (cell, uniqueIndex) {
            // Create content of sub panel
            var $panel = $('<div>...</div>').attr({
                id: 'tblAppendGrid_SubPanelHolder_' + uniqueIndex
            }).appendTo(cell);
        }
    });
});
```

For rows that do not require sub panels:
```javascript
var rows = [1, 3, 5]; // UniqueIndex of rows that are not require sub panel
for (var z = 0; z < rows.length; z++) {
  $('#tblAppendGrid_SubPanelHolder_' + rows[z]).css('display', 'none');
}
```

**Comment by navdeepkaur12** [comment]
Hi @hkalbertl,

Thanks for your reply. I implemented it by hiding the sub panel from rows in which it is not required as you suggested.
