### ISSUE TITLE
Dynamically Adding Column

### ISSUE THREAD

**Issue by srikanthj09** [hkalbertl/jquery.appendGrid#39]
Hi,
Can we have dynamically create columns, after it is intialised.
also can we have inline dom controls edit. instead already visible.
I have tried,
eg:

insertColumn:function (columnsArr) {
        	var columns =columnsArr.columns;
        	var target = this;
            if (target.length > 0) {
            	var tbWhole = target[0];
                var settings = $(tbWhole).data('appendGrid');
                if (settings) {
                	var rows=settings._rowOrder.length;
                }   
            }
            var tbBody = tbWhole.getElementsByTagName('tbody')[0];
            var tbHead = tbWhole.getElementsByTagName('thead')[0];
            var precols=settings.columns.length;
            for (var i=0;i<columns.length;i++){
            	settings.columns.push(columns[i]);
            }
            for (var z = 0 ; z < columns.length; z++) {
            	x=(precols + z);
            	if (settings.columns[x].type != 'hidden') {
	                settings._visibleCount++;
	                settings._finalColSpan++;
	                tbCell = tbHead.rows[0].insertCell(settings._visibleCount);
	                tbCell.className = 'ui-widget-header';
	                $(tbCell).text(settings.columns[x].display);
	                if (settings.columns[x].displayCss) $(tbCell).css(settings.columns[x].displayCss);
	                if (settings.columns[x].headerCellClass) $(tbCell).addClass(settings.columns[x].headerCellClass);//srikanth
	            }
            }
            var tbfoot = tbWhole.getElementsByTagName('tfoot')[0];
            tbfoot.rows[0].cells[0].colSpan = settings._finalColSpan;
            var hidden=[];
            var addCol=0;
            for (var y=0;y< tbBody.rows.length;y++){
            	var uniqueIndex=this.appendGrid('getUniqueIndex',y);
            	hidden.length=0;
            	if(tbBody.rows[y].cells.length>= precols){
	        		for (var x = (0 + precols); x < (columns.length + precols); x++) {
	        			
	        			if (settings.columns[x].type == 'hidden') {
	                        hidden.push(x);
	                        addCol+=1;
	                        continue;
	                    }
	    				tbCell = tbBody.rows[y].insertCell((x-addCol-1));
		                AddColumn(tbWhole,settings,uniqueIndex,x,tbCell);
	                	if (!isEmpty(settings.columns[x].value)) {
	                        setCtrlValue(settings, x, uniqueIndex, settings.columns[x].value);
	                    }
	
	        		}
	        		tbCell=tbBody.rows[y].cells[settings._visibleCount+1];
	        		
	        		for (var j = 0; j < hidden.length; j++) {
	                    ctrl = document.createElement('input');
	                    ctrl.id = settings.idPrefix + '_' + settings.columns[hidden[j]].name + '_' + uniqueIndex;
	                    ctrl.name = ctrl.id;
	                    ctrl.type = 'hidden';
	                    if (!isEmpty(settings.columns[hidden[j]].value)) {
	                        ctrl.value = settings.columns[hidden[j]].value;
	                    }
	                    tbCell.appendChild(ctrl);
	                }
            	}
            }
            //add hidden cols
            saveSetting(tbWhole, settings);
        	return target;
        },

function AddColumn(tbWhole,settings , uniqueIndex , addCol,Cell){
    	var ctrl=null;
    	var y=addCol;
    	if(isEmpty(settings.columns[y])) return null;
        // Insert cell
    	
    	if (isEmpty(Cell)){
    		tbCell=document.createElement('td');
    	}else{
    		tbCell=Cell;
    	}
    	 
        tbCell.className = 'ui-widget-content';
        if (settings.columns[y].cellCss != null) $(tbCell).css(settings.columns[y].cellCss);
        
    	if (settings.columns[y].type == 'custom') {
            if (typeof (settings.columns[y].customBuilder) == 'function') {
                ctrl = settings.columns[y].customBuilder(tbCell, settings.idPrefix, settings.columns[y].name, uniqueIndex);
            }
    	} else if (settings.columns[y].type == 'select') {
	            ctrl = document.createElement('select');
	            ctrl.id = settings.idPrefix + '_' + settings.columns[y].name + '_' + uniqueIndex;
	            ctrl.name = ctrl.id;
	            ctrlOptionsId=settings.columns[y].ctrlOptionsId;
	            ctrlOptionsValue=settings.columns[y].ctrlOptionsValue;
	            // Build option list
	            if ($.isArray(settings.columns[y].ctrlOptions)) {
	                // For array type option list
	            	
	                if (settings.columns[y].ctrlOptions.length > 0) {
	                    if ($.isPlainObject(settings.columns[y].ctrlOptions[0])) {
	                        for (var x = 0; x < settings.columns[y].ctrlOptions.length; x++) {
	                        	if (!isEmpty(ctrlOptionsId)){
	                        		if(x==0 && settings.columns[y].ctrlOptions[0][ctrlOptionsId]!=""){
	                        			ctrl.options[ctrl.options.length] = new Option("", "");
	                        		}
	                    			ctrl.options[ctrl.options.length] = new Option(settings.columns[y].ctrlOptions[x][ctrlOptionsValue], settings.columns[y].ctrlOptions[x][ctrlOptionsId]);
	                        		
	                        	}else{
	                        		if(x==0 && settings.columns[y].ctrlOptions[0].label!=""){
	                        			ctrl.options[ctrl.options.length] = new Option("", "");
	                        		}
	                        		ctrl.options[ctrl.options.length] = new Option(settings.columns[y].ctrlOptions[x].label, settings.columns[y].ctrlOptions[x].value);
	                        	}
	                        }
	                    }
	                    else {
	                        for (var x = 0; x < settings.columns[y].ctrlOptions.length; x++) {
	                        	if (!isEmpty(ctrlOptionsId)){
	                        		if(x==0 && settings.columns[y].ctrlOptions[0][ctrlOptionsId]!=""){
	                        			ctrl.options[ctrl.options.length] = new Option("", "");
	                        		}
	                        		ctrl.options[ctrl.options.length] = new Option(settings.columns[y].ctrlOptions[x][ctrlOptionsValue], settings.columns[y].ctrlOptions[x][ctrlOptionsId]);
	                        	}else{
	                        		if(x==0 && settings.columns[y].ctrlOptions[0]!=""){
	                        			ctrl.options[ctrl.options.length] = new Option("", "");
	                        		}
	                        		ctrl.options[ctrl.options.length] = new Option(settings.columns[y].ctrlOptions[x], settings.columns[y].ctrlOptions[x]);
	                        	}
	//                            ctrl.options[ctrl.options.length] = new Option(settings.columns[y].ctrlOptions[x], settings.columns[y].ctrlOptions[x]);
	                        }
	                    }
	                }
	            } else if ($.isPlainObject(settings.columns[y].ctrlOptions)) {
	                // For plain object type option list
	                for (var x in settings.columns[y].ctrlOptions) {
	                	if (!isEmpty(ctrlOptionsId)){
	                		if(x==0 && settings.columns[y].ctrlOptions[0][ctrlOptionsId]!=""){
	                			ctrl.options[ctrl.options.length] = new Option("", "");
	                		}
	                		ctrl.options[ctrl.options.length] = new Option(settings.columns[y].ctrlOptions[x][ctrlOptionsValue], settings.columns[y].ctrlOptions[x][ctrlOptionsId]);
	                	}else{
	                		if(x==0 && settings.columns[y].ctrlOptions[0]!=""){
	                			ctrl.options[ctrl.options.length] = new Option("", "");
	                		}
	                		ctrl.options[ctrl.options.length] = new Option(settings.columns[y].ctrlOptions[x], x);
	                	}
	                    
	                }
	            } else if (typeof (settings.columns[y].ctrlOptions) == 'string') {
	                // For string type option list
	                var arrayOpt = settings.columns[y].ctrlOptions.split(';');
	                for (var x = 0; x < arrayOpt.length; x++) {
	                    var eqIndex = arrayOpt[x].indexOf(':');
	                    if (-1 == eqIndex) {
	                        ctrl.options[ctrl.options.length] = new Option(arrayOpt[x], arrayOpt[x]);
	                    } else {
	                        ctrl.options[ctrl.options.length] = new Option(arrayOpt[x].substring(eqIndex + 1, arrayOpt[x].length), arrayOpt[x].substring(0, eqIndex));
	                    }
	                }
	            }
	            tbCell.appendChild(ctrl);
	        }
	        else if (settings.columns[y].type == 'checkbox') {
	            ctrl = document.createElement('input');
	            ctrl.type = 'checkbox';
	            ctrl.id = settings.idPrefix + '_' + settings.columns[y].name + '_' + uniqueIndex;
	            ctrl.name = ctrl.id;
	            ctrl.value = 1;
	            tbCell.appendChild(ctrl);
	            tbCell.style.textAlign = 'center';
	            
	        }
	        else if (settings.columns[y].type == 'label') {
	            ctrl = document.createElement('label');
	//            ctrl.type = 'label';
	            ctrl.id = settings.idPrefix + '_' + settings.columns[y].name + '_' + uniqueIndex;
	            ctrl.name = ctrl.id;
	//            ctrl.value = 1;
	            tbCell.appendChild(ctrl);
	            tbCell.style.textAlign = 'center';
	            
	        } else if (settings.columns[y].type == 'hidden') {
	        	ctrl = document.createElement('input');
                ctrl.id = settings.idPrefix + '_' + settings.columns[y].name + '_' + uniqueIndex;
                ctrl.name = ctrl.id;
                ctrl.type = 'hidden';
                if (!isEmpty(settings.columns[y].value)) {
                    ctrl.value = settings.columns[y].value;
                }
                tbCell.appendChild(ctrl);
	        } else if (-1 != settings.columns[y].type.search(/^(color|date|datetime|datetime\-local|email|month|number|range|search|tel|time|url|week)$/)) {
	            ctrl = document.createElement('input');
	            try {
	                ctrl.type = settings.columns[y].type;
	            }
	            catch (err) { /* Not supported type */ }
	            ctrl.id = settings.idPrefix + '_' + settings.columns[y].name + '_' + uniqueIndex;
	            ctrl.name = ctrl.id;
//	            tbCell.appendChild(ctrl);
	            tbCell.appendChild(ctrl);
	        }
	        else {
	            // Generate text input
	            ctrl = document.createElement('input');
	            ctrl.type = 'text';
	            ctrl.id = settings.idPrefix + '_' + settings.columns[y].name + '_' + uniqueIndex;
	            ctrl.name = ctrl.id;
	            tbCell.appendChild(ctrl);
	            // Handle UI widget
                if (settings.columns[y].type == 'ui-datepicker') {
                    $(ctrl).datepicker(settings.columns[y].uiOption);
                } else if (settings.columns[y].type == 'ui-spinner') {
                    $(ctrl).spinner(settings.columns[y].uiOption);
                } else if (settings.columns[y].type == 'ui-autocomplete') {
                    $(ctrl).autocomplete(settings.columns[y].uiOption);
                }
	            
	        }
    	
    	// Add extra control properties
        if (settings.columns[y].type != 'custom') {
        	
            // Add control attributes as needed
            if (settings.columns[y].ctrlAttr != null) $(ctrl).attr(settings.columns[y].ctrlAttr);
            // Add control properties as needed
            if (settings.columns[y].ctrlProp != null) $(ctrl).prop(settings.columns[y].ctrlProp);
            // Add control CSS as needed
            if (settings.columns[y].ctrlCss != null) $(ctrl).css(settings.columns[y].ctrlCss);
            // Add control class as needed
            if (settings.columns[y].ctrlClass != null) $(ctrl).addClass(settings.columns[y].ctrlClass);
            // Add jQuery UI tooltip as needed
            if (settings.columns[y].uiTooltip) $(ctrl).tooltip(settings.columns[y].uiTooltip);
            // Add control events as needed
            if (typeof (settings.columns[y].onClick) == 'function') {
                $(ctrl).click({ caller: tbWhole, callback: settings.columns[y].onClick, uniqueIndex: uniqueIndex }, function (evt) {
                    evt.data.callback(evt, $(evt.data.caller).appendGrid('getRowIndex', evt.data.uniqueIndex));
                });
            }
            if (typeof (settings.columns[y].onChange) == 'function') {
                $(ctrl).change({ caller: tbWhole, callback: settings.columns[y].onChange, uniqueIndex: uniqueIndex }, function (evt) {
                    evt.data.callback(evt, $(evt.data.caller).appendGrid('getRowIndex', evt.data.uniqueIndex));
                });
            }
            if (typeof (settings.columns[y].onBlur) == 'function') {
                $(ctrl).blur({ caller: tbWhole, callback: settings.columns[y].onBlur, uniqueIndex: uniqueIndex }, function (evt) {
                    evt.data.callback(evt, $(evt.data.caller).appendGrid('getRowIndex', evt.data.uniqueIndex));
                });
            }
            if (typeof (settings.columns[y].onKeypress) == 'function') {
                $(ctrl).keypress({ caller: tbWhole, callback: settings.columns[y].onKeypress, uniqueIndex: uniqueIndex }, function (evt) {
                    evt.data.callback(evt, $(evt.data.caller).appendGrid('getRowIndex', evt.data.uniqueIndex));
                });
            }
            if (typeof (settings.columns[y].onKeydown) == 'function') {
                $(ctrl).keydown({ caller: tbWhole, callback: settings.columns[y].onKeydown, uniqueIndex: uniqueIndex }, function (evt) {
                    evt.data.callback(evt, $(evt.data.caller).appendGrid('getRowIndex', evt.data.uniqueIndex));
                });
            }
            if (typeof (settings.columns[y].onKeyup) == 'function') {
                $(ctrl).keyup({ caller: tbWhole, callback: settings.columns[y].onKeyup, uniqueIndex: uniqueIndex }, function (evt) {
                    evt.data.callback(evt, $(evt.data.caller).appendGrid('getRowIndex', evt.data.uniqueIndex));
                });
            }
            
            
            if(!$(ctrl).attr('disabled')){
            	$(ctrl).addClass("dontEnable");
            } 
        }
        return tbCell;
    }

**Comment by chandragie** [comment]
Hi @hkalbertl  I was reading your apendGrid plugin and really love it! I'm kinda newbie here, can you tell me how to populate initData from database? I read the documentation but found no topics about getting the initData (in combobox) from database. I'm using ASP.NET MVC3. Many thanks!

**Comment by hkalbertl** [comment]
Hi @chandragie,

I guess there are [tons of articles](https://www.google.com/search?q=%22asp.net%20mvc%22%20database%20json) on Internet about how to populate data from database via ASP.NET MVC to client side as JSON. You may use any one of them that fit your situation. Once the JSON data loaded, use it to initialize `appendGrid` just like the [basic demo](https://appendgrid.apphb.com/Demo/Basic) did.

Hope it can help. Thanks for using `appendGrid`!

PS: It looks like your question is not related to this topic. May be you can start a post next time :)

**Comment by chandragie** [comment]
HI @hkalbertl , thanks so much for the answer! Actually I was thinking about that way but kinda doubt on trying it. Since now you've given me the very direct solution, I'm gonna use that method! Thanks so much!

**Comment by chandragie** [comment]
Hi again @hkalbertl , (so sorry for double post this in oher closed topic!)
Related to my previous question, I am trying to follow your instruction above, but got error : TypeError : document is undefined in safeFrag method in jquery 1.11.1.js. Can you show which part is wrong in my code? My code is like this:

    $(function () {
        $('#tblAppendGrid').appendGrid({
            columns: [
                { name: 'ProductType', display: 'Product Type', type: 'select' }
            ],
            initRows: 0,
            afterRowAppended: function (caller, parentRowIndex, addedRowIndex) {
                getProductTypes(addedRowIndex);
            },
            afterRowInserted: function (caller, parentRowIndex, addedRowIndex) {
                getProductTypes(addedRowIndex);
            }
        });
    });

    function getProductTypes(rowIndex) {
        var productTypes = $('#tblAppendGrid').appendGrid('getCellCtrl', 'ProductType', rowIndex);
        productTypes = $.getJSON('/Pipeline/GetProductTypes', function (data) {
            // Ajax success callback function. Populate dropdown from Json data returned from server. 
            $(productTypes).remove();
            $(productTypes).append('<option value="">--Pilih Fasilitas--</option>');
            for (i = 0; i < data.length; i++) {
                $(productTypes).append('<option value="' + data[i].ProductTypeNm + '">' + data[i].ProductTypeNm + '</option>');
            }
        }).fail(function (jqXHR, textStatus, errorThrown) {
            // Ajax fail callback function. 
            alert('Error getting product type!');
        });
    }


This is the HTML code:

    <table id="tblAppendGrid"></table>


[UPDATE]
I found out that my JSON is kinda different than how you load it in ctrlOptions:

    [{"ProductTypeNm":"BANK GUARANTEE"},{"ProductTypeNm":"CREDIT CARD"}, "ProductTypeNm":"FOREIGN EXCHANGE"}, {"ProductTypeNm":"INSTALLMENT LOAN"}, "ProductTypeNm":"KMK"},{"ProductTypeNm":"KREDIT EKSPOR"}, {"ProductTypeNm":"KREDIT INVESTASI"}, {"ProductTypeNm":"KREDIT LOKAL"}, {"ProductTypeNm":"LC"}, {"ProductTypeNm":"MONEY MARKET"}, {"ProductTypeNm":"NEGOSIASI/DISKONTO DENGAN KONDISI KHUSUS"}, {"ProductTypeNm":"OBL"}, {"ProductTypeNm":"OMNIBUS"}, {"ProductTypeNm":"SETTLEMENT"}, {"ProductTypeNm":"TIME LOAN"}, {"ProductTypeNm":"TRUST RECEIPT"}]


Is that the problem?

**Comment by chandragie** [comment]
Hi Albert! 
I have posted in your repo about populating dropdownlist via JSON. I will really appreciate your help!

Thank you.


Regards, Chandra Wijaya




On Sun, Jan 17, 2016 at 10:24 PM -0800, "Albert L." <notifications@github.com> wrote:












Hi @chandragie,



I guess there are tons of articles on Internet about how to populate data from database via ASP.NET MVC to client side as JSON. You may use any one of them that fit your situation. Once the JSON data loaded, use it to initialize appendGrid just like the basic demo did.



Hope it can help. Thanks for using appendGrid!



PS: It looks like your question is not related to this topic. May be you can start a post next time :)

**Comment by hkalbertl** [comment]
Back to the original issue on "dynamic add columns", it is still too complicated to implement this feature. So, we may keep using the "work around" approach which is pre-define the columns but hide them after grid initialized and show them as required. Thanks!
