### ISSUE TITLE
Button icons not coming up

### ISSUE THREAD

**Issue by praveens96** [hkalbertl/jquery.appendGrid#40]
I trying to use appengrid. I am not getting the icons as in demo. they are coming as plain buttons without any text.
can someone help me out?

this is my folder structure:
root/
       css/
            Jqueryui
            appendgrid css
             images/
                     icons
       js/
          Jquery
          appengrid js

remaining code as given in the demo.

**Comment by praveens96** [comment]
Albert, is pagination available in appendgrid? how can i keep pagination? can you please help?

**Comment by hkalbertl** [comment]
Hi praveens96,

Sorry that paging is not available. You may take a look on [fix header demo](https://appendgrid.apphb.com/Demo/FixHeader) if you don't want a long table on screen. Thanks!
