### ISSUE TITLE
A subgrid in a subgrid

### ISSUE THREAD

**Issue by bytesfromali** [hkalbertl/jquery.appendGrid#52]
What is the best way of making a subgrid in a subgrid. Is it supported or do we need to make some changes in the code to support it. My code sample:

$('#tblNewTemplateTable').appendGrid({
        caption: 'Enter Template Details',
        initRows: 1,
        columns: [
                { name: 'Section', display: 'Section', type: 'textarea', ctrlAttr: { maxlength: 500 }, ctrlClass: 'form-control' },
                { name: 'hasChildren', display: 'Has Sub-Section', type: 'checkbox' }
        ],
        useSubPanel: true,
        subPanelBuilder: function (cell, uniqueIndex) {
            // Create a table object and add to sub panel
            var subgrid = $('<table></table>').attr('id', 'tblSubGrid_' + uniqueIndex).appendTo(cell);
            // Optional. Add a class which is the CSS scope specified when you download jQuery UI
            subgrid.addClass('alternate col-md-12 col-lg-12 col-sm-12 col-xs-12');
            // Initial the sub grid
            subgrid.appendGrid({
                initRows: 1,
                //hideRowNumColumn: true,
                columns: [
                    { name: 'SubSection', display: 'Sub-Section', type: 'textarea', ctrlAttr: { maxlength: 500 }, ctrlClass: 'form-control' },
                { name: 'hasChildren', display: 'Has Actions', type: 'checkbox' }
                ],
                useSubPanel: true,
                subPanelBuilder: function (cell1, uniqueIndex1) {
                    // Create a table object and add to sub panel
                    var subgrid1 = $('<table></table>').attr('id', 'tblSubSubGrid_' + uniqueIndex1).appendTo(cell1);
                    // Optional. Add a class which is the CSS scope specified when you download jQuery UI
                    subgrid1.addClass('col-md-12 col-lg-12 col-sm-12 col-xs-12');
                    // Initial the sub grid
                    subgrid1.appendGrid({
                        initRows: 1,
                        //hideRowNumColumn: true,
                        columns: [
                            { name: 'Action', display: 'Action', type: 'textarea', ctrlAttr: { maxlength: 500 }, ctrlClass: 'form-control' }
                        ],
                    });
                },
                subPanelGetter: function (uniqueIndex1) {
                    // Return the sub grid value inside sub panel for `getAllValue` and `getRowValue` methods
                    return $('#tblSubSubGrid_' + uniqueIndex1).appendGrid('getAllValue', true);
                },
                rowDataLoaded: function (caller1, record1, rowIndex1, uniqueIndex1) {
                    // Check SubGridData exist in the record data
                    if (record1.SubGridData) {
                        // Fill the sub grid
                        $('#tblSubSubGrid_' + uniqueIndex1, caller1).appendGrid('load', record1.SubGridData);
                    }
                }
            });
        },
        subPanelGetter: function (uniqueIndex) {
            // Return the sub grid value inside sub panel for `getAllValue` and `getRowValue` methods
            return $('#tblSubGrid_' + uniqueIndex).appendGrid('getAllValue', true);
        },
        rowDataLoaded: function (caller, record, rowIndex, uniqueIndex) {
            // Check SubGridData exist in the record data
            if (record.SubGridData) {
                // Fill the sub grid
                $('#tblSubGrid_' + uniqueIndex, caller).appendGrid('load', record.SubGridData);
            }
        }
    });

Items in sub group of each sub-group get same ids. Can you guide me how to resolve this.

**Comment by simon-inman** [comment]
Hi 
Do you still have the sample code for a sub grid in a sub grid as the datafilehost link is no longer valid?
Thanks

**Comment by hkalbertl** [comment]
Hi,

That sample code is not available :(
May be you can take a look on [this sample](https://jsfiddle.net/hkalbertl/jj23zjxL/) hosted on jsfiddle about subgrid of subgrid.

**Comment by hkalbertl** [comment]
Hi @sajwal,

I guess your problem may due to the option on grid or column. 
Could you put your on some online code editor (such as jsfiddle / codepen) for reference?
Alternatively, you may modify my pen [here](https://codepen.io/hkalbertl/pen/jONdRGd) to demonstrate your problem.
