### ISSUE TITLE
Compatibility with bootstrap.js v3.1.0

### ISSUE THREAD

**Issue by alimohammad** [hkalbertl/jquery.appendGrid#54]
As soon as i pull a reference of bootstrap.js script on a page rendering appendGrid all icons turn into blank boxes. Although all functionality works properly except the fact that no icons appear on button after referencing to bootstrap.js.

![image](https://cloud.githubusercontent.com/assets/5945394/5545547/cb59d0a6-8b60-11e4-8ff8-9c12358294c2.png)

**Comment by aveu** [comment]
@alimohammad Did you fix this problem? I'm fighting with the same problem now...

**Comment by hkalbertl** [comment]
@aveu I lost that working sample file but I guess you all you need is to adjust the sequence on CSS and JS files in your HTML page. If I am remembered correctly, please put the jQuery UI CSS in front of bootstrap CSS. Hope it can help :)
