### ISSUE TITLE
Q: Non-input fields

### ISSUE THREAD

**Issue by KarstenD** [hkalbertl/jquery.appendGrid#55]
Hi,
I apologize in advance if it's somewhere in the doc an I didn't notice it :)
But, is it possbile, if so how, to Show also columns with no Input allowed ?
Regards,
Karsten

**Comment by hkalbertl** [comment]
Hi Karsten,

Sorry that I was a little bit busy in these few days.

I guess you wanna to generate a cell with text / image / etc that are not for user input. You can consider to use `Custom Type` (Demo: https://appendgrid.apphb.com/Demo/CustomType) to generate whatever content of a cell that you want. All you need is to implement the three methods:

- customBuilder: generate your custom content (text / image / etc)
- customGetter: just add a return statement for any non-null value (Try not to break the getAllValue method)
- customSetter: leave it as an empty function

Hope I haven't misunderstand your question. Thanks for using `appendGrid`!
