### ISSUE TITLE
hidden input value & name

### ISSUE THREAD

**Issue by robertadsoft** [hkalbertl/jquery.appendGrid#56]
Thank you for your work, I really like the result, it's helping me a lot!

However, I want to point out an issue that I'm currently facing - the hidden type input does not respect the nameFormatter function. Is this how you designed it or is it a bug?

**Comment by hkalbertl** [comment]
Hi robertadsoft,

This is a bug and I will prepare an update shortly. Thanks!

**Comment by hkalbertl** [comment]
Hi again,

Please check the latest version which is v1.5.2 that fixed this issue.
Thanks for reporting!
