### ISSUE TITLE
Make tbody of appendgrid scroll

### ISSUE THREAD

**Issue by niftyhawk** [hkalbertl/jquery.appendGrid#58]
Is it possible to support scrolling only for the tbody like this example:

http://pics.cssbakery.com/treats/scrollingtable/tableTest10.php

or 

http://www.scientificpsychic.com/blogentries/html-and-css-scrolling-table-with-fixed-heading.html

The intent is to keep the header and footer fixed. But allow the tbody of the table to scroll such that even though there are 50+ rows, the height of the widget is constant.

Thanks

**Comment by hkalbertl** [comment]
Hi niftyhawk,

I tried to work on "fixed header" on `appendGrid` a few months ago but I there are some problems found:

- No standard for tbody scrolling all web browsers
- Cannot find a way to keep current `appendGrid` appearance with scrolling feature

I know it is a problem for a long grid (because I got it already) but I guess it is not possible to add this feature as this moment. I will keep looking for a solution / alternative for this. Thanks!

**Comment by hkalbertl** [comment]
Hi again,

I got an idea on this issue now and I made some changes (quite a lot actually) for that. I am still working on testing it but you may take a look here: http://jsfiddle.net/hkalbertl/xk3rnu6n/

Thanks!

**Comment by niftyhawk** [comment]
Hi Albert,

Thanks a lot for looking into it and putting the extra effort. Really appreciate it and it's looking much better now.

Just a few comments though for a better user experience:

1. When you try to add a new row using the "+" button or delete an existing row using the "x" button in the footer, is it possible to automatically scroll to the bottom, showing the last row? It would be much more user friendly if we did this, especially if you have more rows.

2. I noticed that the scroll bar itself is hanging to the right of the tbody (sort of looking detached from the entire widget). Is it possible to make it work as though it's part of the widget, like this example:

http://pics.cssbakery.com/treats/scrollingtable/tableTest10.php

Thank you very much and keep up the great work.

**Comment by hkalbertl** [comment]
Hi,

1. Yes, I notice that as well, I will add something like the `maintainScroll` feature for it. (Just found that no documentation for it but this feature was developed for a while)

2. In your example, all columns' width are fixed and defined in CSS which may not suitable in our case. Let me check it again later.

Thanks!

**Comment by hkalbertl** [comment]
Hi again,

I tried the example that you gave me in previous comment but it seems that the `tfoot` section cannot be fixed. As I said before, you are required to specified the width of each column (in thead and tbody) and in the scroll container.

I guess I will back to investigate on my approach. If you really want to make a scrolling `appendGrid` with your example's style, please check my testing jsfiddle here: http://jsfiddle.net/hkalbertl/6djL2t92/

Thanks!

**Comment by hkalbertl** [comment]
Hi, please check the latest version of `appendGrid` for scrollable tbody. A demo is available [here](https://appendgrid.apphb.com/Demo/FixHeader). Cheer~
