### ISSUE TITLE
How to populate SQL DB values in apprendgrid table

### ISSUE THREAD

**Issue by quls** [hkalbertl/jquery.appendGrid#59]
@hkalbert 
i'm using apprendgrid control in my form and developing the application using ASP.Net (MVC5) , I'm facing the problem to get DB values from different tables and populate into apprendgrid , please suggest me how i can get SQL Server values.
If possible , create tutorial for ASP.Net(MVC5) to get and saving the values into DB.

thanks in advance , please reply as soon as possible because it urgent work that need to finish this week. Really thanks 

Table columns name:
ID, Last Name , First name, Age , SSN , Race , Language

**Comment by hkalbertl** [comment]
Hi quls,

Sorry that I know have a PC running Visual Studio 2012 which is required for MVC5. So, I just create a sample solution that using VS2010 + MVC4. I guess the concept is the same so you can take a look to see how to retrieve data. In this sample solution, you can see:

- Data stored in MDF file under App_Data of MVC web application
- Serve data in JSON format by using a controller
- Using jQuery AJAX function to retrieve data

Download: http://www.datafilehost.com/d/659a23e7

Hope it can help, good luck for your project!
