### ISSUE TITLE
Is it possible to add search to this grid?

### ISSUE THREAD

**Issue by niftyhawk** [hkalbertl/jquery.appendGrid#61]
I think it should be possible to add a search box to this grid. When the user types, a regex match could occur s as he is typing and it can show only those rows whose data it matched. What do you think? It would be a nice feature enhancement. :)

**Comment by hkalbertl** [comment]
Hi niftyhawk,

Searching is always a nice feature for big dataset. But the next question is how to let end users to search? I have to solve these questions before implement the search feature:

- Pop up a dialog for input search text? Or add a textbox under the column header (or somewhere else)?
- I agreed regex is a good option for searching, but it may not a good choice for non-technical users.
- A single textbox to search all column? Or generate 10 textboxes if you have 10 columns?
- How about searching on number / date / custom type?
- How to indicate the rows that are matched search criteria? Highlight them? Or hide others rows?
- Needed to handle searching when some columns are hide

I am afraid that this enhancement will not able to complete in a short time. But I will keep in mind for this enhancement and try to work on that later.
Thanks for using `appendGrid`.
