### ISSUE TITLE
Issues using buttonClasses setting

### ISSUE THREAD

**Issue by pbreah** [hkalbertl/jquery.appendGrid#62]
I found an error on the .addClass() method that uses a (,) comma instead of a + to append classes.

This causes the .addClass() not to append the custom classes to the buttons.

For example the custom classes won't work with:

.addClass('moveDown', settings._buttonClasses.moveDown)

but work with:

.addClass('moveDown '+ settings._buttonClasses.moveDown)

Thanks

**Comment by hkalbertl** [comment]
Hi pbreah,

Properly it is a problem on jQuery.
I would like to ask which version of jQuery are you using? Thanks!

**Comment by pbreah** [comment]
I'm using what the current version of Wordpress has: jQuery v1.11.2 and jQuery Migrate v1.2.1

I checked the official jQuery docs, and there is no mention of passing multiple classes as separate parameters: https://api.jquery.com/addclass/ , could this be an overridden .addClass() method on your end?

Thanks

**Comment by hkalbertl** [comment]
Oops, you are correct. I may mix up it with some other function.
The fix will be available in next release. Thanks!

**Comment by pbreah** [comment]
No problem, glad to help :-)

Great work on this jQuery plugin, very useful.

**Comment by hkalbertl** [comment]
Hi, a new version of `appendGrid` is released which fixed this issue. Cheer~
