### ISSUE TITLE
How to get the value of custom column on server side

### ISSUE THREAD

**Issue by rasikrodri** [hkalbertl/jquery.appendGrid#63]
I can get the values, on server side, of all the normal columns but the custom column values are not there.
How can I get those values of the custom column?
Even when I examin "Request.Form" all the normal columns are there but not the custom ones.

**Comment by hkalbertl** [comment]
Hi rasikrodri,

I guess you are trying to `post` all your input fields to server. So, you are required to specified the name of `input` generated in your custom column.

For example, in the my `Custom Type` demo (Url: https://appendgrid.apphb.com/Demo/CustomType), you should add the `name` to the generated `input` type at line 19~21. Such as:
```javascript
$('<input>', { type: 'text', id: ctrlId + '_Hour', name: ctrlId + '_Hour' }).appendTo(ctrl);
```

I will update the demo coding to specify the `name` soon, thanks!

**Comment by rasikrodri** [comment]
Thank you for your prompt aswer. This is an amazing plugin!
In my custom column I am placing more than one control, for example: a read only textbox that works as a lable, a checkbox and a dropdow. I need to get the values for all the those controls.  That is basicaly what I have to do.
I create custom columns with all the controls needed and then in some rows I set some of those controls to 'display = none' so that they are not visible according to what the row is all about.

**Comment by hkalbertl** [comment]
Yeah! That is the main purpose of `Custom Type`. You can customize the the columns to fit your needs!

`appendGrid` will be updated from time to time. Feel to come back later and take a look on the new features. Thanks for using `appendGrid`!

By the way, the demo code is updated that will include the `name` attribute in generated `input` type.

**Comment by rasikrodri** [comment]
Thank You very much. This is working like a charm.
