### ISSUE TITLE
how to dynamically  load option values in select 

### ISSUE THREAD

**Issue by chetan-sminq** [hkalbertl/jquery.appendGrid#64]
Hi,

one of my column in appendgrid is a input type of select.

as per the examples , one can use the select as follows 
{ name: 'Origin', display: 'Origin', type: 'select', ctrlOptions: { 0: '{Choose}', 1: 'Hong Kong', 2: 'Taiwan', 3: 'Japan', 4: 'Korea', 5: 'US', 6: 'Others'} },

but my ctrlOptions list is dynamic which i get through an api call. I get the json string as required above but when i try to substitute the json variable then i dont know why part of string till the first occurance of  ":" is removed

example: var data="{1:'Mango',2:'Banana',3:'Milk'}";

{ name: 'Origin', display: 'Origin', type: 'select', ctrlOptions: data},

so this will produce a select with only one option with value 'Mango',2:'Banana',3:'Milk'}  

How to i solve it to produce proper options

**Comment by hkalbertl** [comment]
Hi chetan-sminq,

There is no such feature in `appendGrid` at this moment. But you can build the options once a row is appended / inserted. For example:

```javascript
$(function() {
	$('#tblAppendGrid').appendGrid({
		columns: [
			{ name: 'dropdown', display: 'Drop down', type: 'select' }
		],
		initRows: 0,
		afterRowAppended: function (caller, parentRowIndex, addedRowIndex) {
			generateOptions(addedRowIndex);
		},
		afterRowInserted: function (caller, parentRowIndex, addedRowIndex) {
			generateOptions(addedRowIndex);
		}
	});
});
function generateOptions(rowIndex) {
	var theSelectElement = $('#tblAppendGrid').appendGrid('getCellCtrl', 'dropdown', rowIndex);
	$(theSelectElement).empty().append($('<option></option>').text('Option 1').val(1)).append($('<option></option>').text('Option 2').val(2));
}
```

Hope it can help. Thanks for using `appendGrid`!

**Comment by chandragie** [comment]
Hi again @hkalbertl ,
Related to my previous question in other thread, I am trying to follow your instruction above, but got error : TypeError : document is undefined in safeFrag method in jquery 1.11.1.js. Can you show which part is wrong in my code? My code is like this:

    $(function () {
        $('#tblAppendGrid').appendGrid({
            columns: [
                { name: 'ProductType', display: 'Product Type', type: 'select' }
            ],
            initRows: 0,
            afterRowAppended: function (caller, parentRowIndex, addedRowIndex) {
                getProductTypes(addedRowIndex);
            },
            afterRowInserted: function (caller, parentRowIndex, addedRowIndex) {
                getProductTypes(addedRowIndex);
            }
        });
    });

    function getProductTypes(rowIndex) {
        var productTypes = $('#tblAppendGrid').appendGrid('getCellCtrl', 'ProductType', rowIndex);
        productTypes = $.getJSON('/Pipeline/GetProductTypes', function (data) {
            // Ajax success callback function. Populate dropdown from Json data returned from server. 
            $(productTypes).remove();
            $(productTypes).append('<option value="">--Pilih Fasilitas--</option>');
            for (i = 0; i < data.length; i++) {
                $(productTypes).append('<option value="' + data[i].ProductTypeNm + '">' + data[i].ProductTypeNm + '</option>');
            }
        }).fail(function (jqXHR, textStatus, errorThrown) {
            // Ajax fail callback function. 
            alert('Error getting product type!');
        });
    }


This is the HTML code:

    <table id="tblAppendGrid"></table>
