### ISSUE TITLE
Can you give an example what to do after remove by using AppendGrid??

### ISSUE THREAD

**Issue by Chhunmeng** [hkalbertl/jquery.appendGrid#65]

**Comment by hkalbertl** [comment]
Hi,

Do you mean how to handle row removed event? You can make use of `afterRowRemoved` callback. For example:

```javascript
$('#tblAppendGrid').appendGrid({
  columns: [ /* Columns definition */ ],
  afterRowRemoved: function (caller, rowIndex) {
    // Do something after a row is removed
  }
});
```

Hope it can help :)

**Comment by Chhunmeng** [comment]
Hello sir,

Thanks for reply back to me.
Now I'm using AppendGrid.
I try to see your  tutorial again and again.
I want you to create more example and detail example in your tutorial.

Thanks you!
Chhunmeng




Best Regards,
Chhunmeng
-------------------------------------------------------------------------------------------------
*Mr.* *CHHOM CHHUNMENG*
The student of Computer Science, Royal University of Phnom Penh
Tel: (+855)10 726 443
Email: chhom.chhunmeng@gmail.com
Address: Phnom Penh
-------------------------------------------------------------------------------------------------

**Comment by hkalbertl** [comment]
Hi,

There are several example with source code available at [appendGrid website](https://appendgrid.apphb.com/Demo).

May be you can make some suggestions or tell me the problems that you facing. So, I can consolidate and put them as example in appendGrid website to help others. Thanks!

**Comment by Chhunmeng** [comment]
Hi,

Chhunmeng Chhom wants to connect with you on LinkedIn.
Join now to view their profile and start your own.

Confirm that you know Chhunmeng: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=54FoOSP4&invitationId=6206472943237722119&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-2-null-null-0%7Eivs6hmy2%7Enc








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ivs6hmy2-nc&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQFtS3RtbTzhawAAAViHU7lFFNy5M2BnS09xQ0kgdvdFDq8YUSfUNIvMmw_M_VAh8bpduSs7FIKzf_8DE3CB5HnrFqDVaWLRat1CTedBcSraDJC4i_StRY3cN8KywKx7OpIhqc8jBDcWmLg8q_LfSfvkQltN99oxmNYFNgBhoIxNXpvrk2baxKmK5Kdmw9ZVdcEE&eid=0-ivs6hmy2-nc


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ivs6hmy2-nc&a=customerServiceUrl&ek=invite_guest

© 2016 LinkedIn Corporation, 1000 West Maude Avenue, Sunnyvale, CA 94085. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by Chhunmeng** [comment]
Chhunmeng Chhom would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=54FoOSP4&invitationId=6206472943237722119&trk=eml-first_guest_reminder_01-hero-121-accept_text&trkEmail=eml-first_guest_reminder_01-hero-121-accept_text-null-%7Ewojg4b%7Eiw2tstpr%7Enk

View Chhunmeng Chhom&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=54FoOSP4&invitationId=6206472943237722119&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-%7Ewojg4b%7Eiw2tstpr%7Enk





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-wojg4b-iw2tstpr-nk&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=123&m=unsub&ts=HTML&eid=-wojg4b-iw2tstpr-nk&loid=AQEcMpgQNXTLOAAAAViuf2M1tceEXYwFaLzmq5_MH1AwnBAZh5eKJk_XfmWUhFOvTMuZ1zRaJFNblqD9C4uJvQz0Lzo8UWTk4Sd1i82DmO-QudkP1TqyOZhX6LjqB8HicQtUqHWtU257iM5CFjJ-2SkGsoiIyUgJ5rf8rzPtNuLV-VpVzPsIVDLjTFxUakAjoHgVG2LtMCjyu54hODFxFSnjdGxCVg

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-wojg4b-iw2tstpr-nk&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by Chhunmeng** [comment]
Hi ,

Chhunmeng Chhom would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=54FoOSP4&invitationId=6206472943237722119&trk=eml-second_guest_reminder_01-hero-120-accept_text&trkEmail=eml-second_guest_reminder_01-hero-120-accept_text-null-%7Ewojg4b%7Eiwctrv81%7Ely

View Chhunmeng Chhom&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=54FoOSP4&invitationId=6206472943237722119&trk=eml-second_guest_reminder_01-hero-3-profile_text&trkEmail=eml-second_guest_reminder_01-hero-3-profile_text-null-%7Ewojg4b%7Eiwctrv81%7Ely





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-wojg4b-iwctrv81-ly&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=122&m=unsub&ts=HTML&eid=-wojg4b-iwctrv81-ly&loid=AQFrtcfuBGH8WwAAAVjS8ITjMk8JPYhS67sn-kVcmbqrNddJg-Zhaxy0ENX5qVytAJlsOajO5FmATUDg78sU3R-hvWQnv1QrDlK1dOWAepva80ldCA6GnEL2IQZFclnOHAisHaF-8Jrg-Yu8miF6R7Fp-gEr4CJxhnywvTzWy1OkBaU-RTb4XYXpSP1eQzEpcd41EWBrZo1RMUCroUxY5eWi0ML_aQ

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-wojg4b-iwctrv81-ly&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
