### ISSUE TITLE
Check box column check boxes return wrong values

### ISSUE THREAD

**Issue by rasikrodri** [hkalbertl/jquery.appendGrid#66]
When the check box is checked it returns "1"
First time that it is unchecked it returns "1, on"    -------- This is what i do not understand, I expect Nothing.
Second time checked it returns "1"
Second time unchecked returns Nothing

Thank You in advance

**Comment by hkalbertl** [comment]
Hi rasikrodri,

I tested on the latest `appendGrid` and I cannot reproduce your problem. Can you provide sample code (such as jsfiddle) for reference? Thanks!

**Comment by rasikrodri** [comment]
I see I do not have the latest version. I will test with it first and will let you know.

Thank You

**Comment by rasikrodri** [comment]
It works with the latest version. Thank You.

**Comment by hkalbertl** [comment]
Good to know. Thanks for using `appendGrid`!
