### ISSUE TITLE
"afterRowSwapped" not fireing and "afterRowDragged" getting "uniqueIndex" as null

### ISSUE THREAD

**Issue by rasikrodri** [hkalbertl/jquery.appendGrid#67]
This is the code:

//Html
<div class="col-sm-7" style="padding-left:0px; padding-right:0px">
        <div id="pieChart"></div>
</div>

// Javascript code

// Set up the data
    this.data = [
	    { label: "Basic", color: "#3366CC", value: 50 },
	    { label: "Plus", color: "#3366CC", value: 20 },
	    { label: "Lite", color: "#3366CC", value: 15 },
	    { label: "Elite", color: "#3366CC", value: 10 },
	    { label: "Delux", color: "#3366CC", value: 5 }
    ];

function OnRowSwapped(caller, oldRowIndex, newRowIndex) {
    
  }

function OnRowDragged(caller, rowIndex, uniqueIndex) {

  }

this.chartEditor_AppendGrid = $('#tblChartData')

    // Initialize appendGrid
    this.chartEditor_AppendGrid.appendGrid({
      caption: '',
      //      initRows: 1,
      maxBodyHeight: 590,
      hideRowNumColumn: true,
      rowButtonsInFront: true,
      rowDragging: true,
      afterRowSwapped: function (caller, oldRowIndex, newRowIndex) {
        OnRowSwapped(caller, oldRowIndex, newRowIndex);
      },
      afterRowDragged: function (caller, rowIndex, uniqueIndex) {
        OnRowDragged(caller, rowIndex, uniqueIndex);
      },
      maintainScroll: true,
      hideButtons: {
        append: false,
        removeLast: true,
        insert: true,
        remove: false,
        moveUp: true,
        moveDown: true
      },
      columns: [
            { name: 'label', display: 'Name', type: 'text', ctrlAttr: { maxlength: 100 }, ctrlCss: { width: '160px', 'font-size': '15px', 'border': 'none', 'border-collapse': 'inherit' }, displayCss: { 'color': 'white' }, cellCss: { 'border': 'none' },
              onChange: function (evt, rowIndex) { OnRowValuesChanged(evt, rowIndex); }
            },
            { name: 'value', display: 'Amout', type: 'number', ctrlAttr: { maxlength: 100 }, ctrlCss: { width: '100px', 'font-size': '13px', 'border': 'none', 'border-collapse': 'inherit' }, displayCss: { 'color': 'white' }, cellCss: { 'border': 'none' },
              onChange: function (evt, rowIndex) { OnRowValuesChanged(evt, rowIndex); }
            }
        ],
      customGridButtons: {
        // Use a DOM element
        append: function () {
          var button = document.createElement('button');
          button.type = 'button';
          button.title = 'Append Row';
          //          button.style.padding = "1px 0px 1px 0px";//Centers the icon
          var span = document.createElement('span');
          span.setAttribute('class', 'glyphicon glyphicon-plus');

          button.appendChild(span);
          //          button.textContent = 'Add';
          return button;
        },
        remove: function () {
          var button = document.createElement('button');
          button.title = 'Remove Row';
          button.style.marginLeft = "0px"; //Centers the icon
          button.style.marginRight = "0px"; //Centers the icon
          button.style.padding = "1px 0px 1px 0px"; //Centers the icon
          var span = document.createElement('span');
          span.setAttribute('style', 'font-size: .8em');
          span.setAttribute('class', 'glyphicon glyphicon-trash');
          button.appendChild(span);
          return button;
        }
      },
      sectionClasses: {
        caption: 'header',
        header: 'header',
        footer: 'footer',
        body: ''
      }
    });

    //Add the data
    this.chartEditor_AppendGrid.appendGrid('load', this.data);

**Comment by hkalbertl** [comment]
Hi rasikrodri,

I checked that `afterRowSwapped` callback should be fine. This event will be fired once a row moved up or down.

For the `afterRowDragged` callback, I confirm that there is a problem on passing `uniqueIndex`.

I will prepare an update shortly. Thanks for reporting!

**Comment by hkalbertl** [comment]
Hi,

I just committed `appendGrid` v1.6.1 that fixed the `afterRowDragged` callback problem. Thanks!

**Comment by rasikrodri** [comment]
I see, "afterRowSwapped" has nothing to do with draggin. Is for when the buttons of moving row up or down are pressed.

Thank You.

**Comment by hkalbertl** [comment]
You are correct. I will update the documentation to clarify `afterRowSwapped` callback. Thanks!

**Comment by rasikrodri** [comment]
Thank you, uniqueIndex has the value now.

**Comment by rasikrodri** [comment]
As I understand uniqueIndex showld have the index of the draged item before it was dragged to a new index. But sometimes it has the wrong value, it some times gives me an index less than what is supposed to be. If you drag aroung a few items you will see it.

**Comment by rasikrodri** [comment]
Ups, my brain was already fried by the time I wrote the last comment. Unique
index is asigned to every row when get created and it does not change ever. It is inmutable. 

Thank You for the great work

**Comment by hkalbertl** [comment]
No problem. Thanks for using `appendGrid`!
