### ISSUE TITLE
Conflict with bootstrap

### ISSUE THREAD

**Issue by changbaishan** [hkalbertl/jquery.appendGrid#68]
jquery.appendGrid cannot be used along side Bootstrap(getbootstrap.com). Please consider resolving the conflict. .

**Comment by hkalbertl** [comment]
Hi,

Do you encounter the same problem of #54?? If not, can you tell me in more detail what is your problem? Thanks!

**Comment by hkalbertl** [comment]
Hi again,

Please check my new test case [here](https://github.com/hkalbertl/jquery.appendGrid/blob/master/test/Bootstrap.html) and notice the order of javascript include statements. Hope it can help. Thanks!

**Comment by changbaishan** [comment]
Thanks for the email! And thank you for open source your wonderful appendGrid!
In response to your request of describing the conflict: I have tried 1.52 and 1.61 releases. What happened was appnedGrid does not show as soon as boostrap.js was added. My best guess was a conflict between boostrap.css and appendgrid.css. 
I noticed that your test case is done with development version of appendgrid. It will be wonderful if the issue get resolved. As you know, a lot more people use bootstrap. When issues come up, they tend to give up appendGrid rather than bootstrap.  
Please feel free to close the issue on github. Please let me know if you need me do it.
Thanks again for your software and your attention.
Yong Liu


Date: Fri, 2 Oct 2015 10:30:26 -0700

**Comment by hkalbertl** [comment]
Good to know the new test case is working fine.

By the way, the development version should be the same as v1.6.1 since no changes made after that release. May be you can try again by using v1.6.1 in your website / application. If problem is still there please let me know :smile:

For your suggestion about Bootstrap, may be I can add some more demo / sample code for using Bootstrap so that developers can integrate `appendGrid` and Bootstrap easily.

Thanks for using appendGrid.

**Comment by changbaishan** [comment]
Adding a bootstrap related demo is a good idea. Demo is one of your strength.
Best regards,
Yong Liu

Date: Tue, 6 Oct 2015 23:00:42 -0700

**Comment by hkalbertl** [comment]
Hi again,

The Bootstrap demo is now available on `appendGrid` website. You may check it [here](https://appendgrid.apphb.com/Demo/Bootstrap). Thanks!

**Comment by changbaishan** [comment]
Thank you very much for your help.
Yong 

Date: Mon, 19 Oct 2015 08:55:33 -0700
