### ISSUE TITLE
Load data not populating select input

### ISSUE THREAD

**Issue by boulepick** [hkalbertl/jquery.appendGrid#69]
First let me say great plugin.
let me show my setup 

$(function () {
    $('#tblAppendGrid').appendGrid({
        caption: 'Certifications',
        columns: [
            { name: 'specialtyid', display: 'Certification', type: 'select',  ctrlOptions: generateOptions , ctrlCss: { width: '250px' }, onChange: handleChange },
			{ name: 'dateObtained', display: 'Date Obtained', type: 'ui-datepicker', ctrlAttr: { maxlength: 10 }, ctrlCss: { width: '80px' }, uiOption: { dateFormat: 'yy/mm/dd'}, onChange: handleChange },],
        initData: [{ specialtyid: 5, dateObtained: '10/11/2015'}]
    });
	 $('#tblAppendGrid').appendGrid('load', [
	  {specialtyid: 3,"dateObtained":"07\/16\/2015"},{specialtyid:4,"dateObtained":"03\/12\/2015"},{specialtyid:5,"dateObtained":"03\/10\/2015"},{specialtyid:6,"dateObtained":"03\/10\/2015"}]);
});

generateOptions is an ajax call and returns the data. that works fine, I'm able to see the list, the issue is that i cannot init nor load the data for the select input. the date field works ok for init and load. Am i do ing something wrong for the select field or is this an issue?

Thanks for the help

**Comment by hkalbertl** [comment]
Hi boulepick,

As your `generateOptions` is an AJAX function, the select input options will be generated after the `appendGrid('load', ...)`. May be I would say in another way, the `load` function will not wait for the `generateOptions` function completed and then fill in your data.

Is that your select input options must be generated in `load` function?
If the answer is no, please prepare the options before you call the `load` function and make use of the `rowDataLoaded` callback to fill in data of each row. (Demo: https://appendgrid.apphb.com/Demo/DropDownList)

Otherwise, please consider the following workaround:
```javascript
$(function () {
	$('#tblAppendGrid').appendGrid({
		caption: 'Certifications',
		columns: [
			/* Add a temp hidden column which is not visible on screen */
			{ name: 'specialtyid_temp', type: hidden },
			{ name: 'specialtyid', display: 'Certification', type: 'select', ctrlOptions: generateOptions , ctrlCss: { width: '250px' }, onChange: handleChange },
			{ name: 'dateObtained', display: 'Date Obtained', type: 'ui-datepicker', ctrlAttr: { maxlength: 10 }, ctrlCss: { width: '80px' }, uiOption: { dateFormat: 'yy/mm/dd'}, onChange: handleChange }
		],
		initData: [{ specialtyid_temp: 5, dateObtained: '10/11/2015'}],
		
	});
	$('#tblAppendGrid').appendGrid('load', [
		/* Load the value to `specialtyid_temp` hidden first */
		{specialtyid_temp: 3,"dateObtained":"07\/16\/2015"},
		{specialtyid_temp:4,"dateObtained":"03\/12\/2015"},
		{specialtyid_temp:5,"dateObtained":"03\/10\/2015"},
		{specialtyid_temp:6,"dateObtained":"03\/10\/2015"}
	]);
});
function generateOptions(elem) {
	$.ajax({
		/* Your AJAX call setting */
	}).done(function (result) {
		/* Your code for handle AJAX result */
		$(elem).append(/* Generate your options here */);
		
		/* Find the rowIndex */
		var uniqueIndex = elem.id.substring(elem.id.lastIndexOf('_') + 1);
		var rowIndex = $('#tblAppendGrid').appendGrid('getRowIndex', uniqueIndex);
		
		/* Get the select input value from hidden */
		var specialtyid = $('#tblAppendGrid').appendGrid('getCtrlValue', 'specialtyid_temp', rowIndex);
		
		/* Set the select input value */
		$('#tblAppendGrid').appendGrid('setCtrlValue', 'specialtyid', rowIndex, specialtyid);
	});
}
```

Hope it can help. Thanks for using `appendGrid`!

**Comment by boulepick** [comment]
Thanks Albert for the quick response, i made it work but with the work around but i find that it is making multiple ajax call for each of the row. it would be better to have one ajax call, store the options in a variable and generate the rows of that one variable and prevent multiple repeated ajax calls. Imagine we have a table with 100 rows, the way this it is currently setup it would have to make 100 ajax call. your thoughts and option.

**Comment by hkalbertl** [comment]
Good to know :smile:
Good luck in your development / project!

**Comment by boulepick** [comment]
need your help on one more thing Albert. took your advice on the code and made it work just as you suggested, however i modified it a little bit to not have multiple ajax call but rather one ajax call to get the list and generate the options with the stored result.
so i have a global variable that store the json result like this.

specList = loadUserList('/ajaxx/ajax.getSpecList.php' );

and then i modified the generateOptions function  this way:

function generateOptions(elem) {

   $.each(specList, function(index, value) {
	   $(elem).append(new Option(value, index));
   });

   /* Find the rowIndex */
   var uniqueIndex = elem.id.substring(elem.id.lastIndexOf('_') + 1);
   var rowIndex = $('#SpecGrid').appendGrid('getRowIndex', uniqueIndex);

   //* Get the select input value from hidden */
   var listID = $('#SpecGrid').appendGrid('getCtrlValue', 'temp', rowIndex);

   // /* Set the select input value */
  $('#SpecGrid').appendGrid('setCtrlValue', specialtyid, rowIndex, listID);
}
i get an undefined value for listID and error on the last line $('#SpecGrid').appendGrid('setCtrlValue', specialtyid, rowIndex, listID); but if i remove the that line.

the code will run ok without that line but won't select the user options as intended.

**Comment by hkalbertl** [comment]
Hi,

1. Can you make sure the column `temp` is there and values can be loaded to this column during `load` / `initData` function?
2. In this line `$('#SpecGrid').appendGrid('setCtrlValue', specialtyid, rowIndex, listID);`, `specialtyid` is a variable. Are you sure this value is assigned?

However, I can see that your drop down list option is now `static`. So, I suggest you to convert your options to object array and use it as `ctrlOptions` (Demo [here](https://appendgrid.apphb.com/Demo/DropDownList), line 22 to 33. The property `group` is not required in your case). If so, you will not need the `generateOptions` function anymore and selected values can be loaded into grid directly.

**Comment by boulepick** [comment]
Hi Albert, 
yes the column is there and has values, even put it as text type to see and values are showing in the temp column. the specialtyid is being assigned because when i remove the last row where we set the select input value it works fine, all the list get populated in all rows without the user selected values.
 the only thing that changed from the code is the removal of the ajax call and the .done(function(data){} after the ajax call. is it possible since that wait period is not there from the .done() function that js is running the code asynchronously and not allowing the create select options to complete in the $.each function before getting the select input value from hidden column. that being said i think it is strange because the two prior variable are created with no issues (uniqueIndex and rowIndex). i'm a little bit lost here.

I know it has nothing to do with your plug-in but thanks again for the help.

cheers
