### ISSUE TITLE
Bootstrap 3 Datepicker UI Widget compatibility

### ISSUE THREAD

**Issue by boulepick** [hkalbertl/jquery.appendGrid#70]
Hi Albert,

Just a suggestion, is it possible to add compatibility with this jquery widget "Bootstrap 3 Datepicker" it is a nifty little widget that would be a great addition to this plug-in. it could replace or be a supplement to the Jquery Date Picker UI widget, it has way more option that the base Jquery Date Picker.

**Comment by hkalbertl** [comment]
Hi boulepick,

As `appendGrid` is based on jQuery UI so it would be good to keep supporting the jQuery UI Datepicker.

Also, there are tons of jQuery plugin nowadays so I afraid it is not possible to make `appendGrid` to support a specified plugin natively. I have checked their demo (I guess you are talking about [this one](https://eonasdan.github.io/bootstrap-datetimepicker/)) and I guess it should be fine to use it as `Custom Type` in `appendGrid` (Demo [here](https://appendgrid.apphb.com/Demo/CustomType)). May be you can try it first and let me know (with sample code / jsfiddle) when there are problems. Thanks!

**Comment by boulepick** [comment]
Ok thanks i will try and let you know how it went.

Cheers
