### ISSUE TITLE
Unique Index Selection 

### ISSUE THREAD

**Issue by srinivaschanda** [hkalbertl/jquery.appendGrid#74]
I want to be able to select unique index number, and popup all the information related to row.

**Comment by hkalbertl** [comment]
Hi,

Have you tried [getUniqueIndex](https://appendgrid.apphb.com/Documentation#link-getUniqueIndex) and [getRowValue](https://appendgrid.apphb.com/Documentation#link-getRowValue)?

**Comment by srinivaschanda** [comment]
Hi Albert, 
i was able to retrieve information using the above methods. 
but i cannot click on those numbers ( 1, 2, 3, 4, 5..)
when i click on those row number, i should able to show / popup information related to that row

**Comment by hkalbertl** [comment]
I see. I was misunderstood your question.
So, you can add the following code for handling the click event on the row number

```javascript
$('#tblAppendGrid').on('click', 'tbody tr td.first', function() {
	var uniqueIndex = this.parentNode.id.substring(this.parentNode.id.lastIndexOf('_')+1);
	alert(uniqueIndex); // Do whatever you wanted by using the uniqueIndex!!
});
```

Hope it can help :)

**Comment by srinivaschanda** [comment]
thanks Albert, this code help a lot for me
