### ISSUE TITLE
Dynamic Combobox Using JSON

### ISSUE THREAD

**Issue by chandragie** [hkalbertl/jquery.appendGrid#75]
Hi again @hkalbertl , (so sorry for double post this in oher closed topic!)
Related to my previous question, I am trying to follow your instruction above, but got error : TypeError : document is undefined in safeFrag method in jquery 1.11.1.js. Can you show which part is wrong in my code? My code is like this:

    $(function () {
        $('#tblAppendGrid').appendGrid({
            columns: [
                { name: 'ProductType', display: 'Product Type', type: 'select' }
            ],
            initRows: 0,
            afterRowAppended: function (caller, parentRowIndex, addedRowIndex) {
                getProductTypes(addedRowIndex);
            },
            afterRowInserted: function (caller, parentRowIndex, addedRowIndex) {
                getProductTypes(addedRowIndex);
            }
        });
    });

    function getProductTypes(rowIndex) {
        var productTypes = $('#tblAppendGrid').appendGrid('getCellCtrl', 'ProductType', rowIndex);
        productTypes = $.getJSON('/Pipeline/GetProductTypes', function (data) {
            // Ajax success callback function. Populate dropdown from Json data returned from server. 
            $(productTypes).remove();
            $(productTypes).append('<option value="">--Pilih Fasilitas--</option>');
            for (i = 0; i < data.length; i++) {
                $(productTypes).append('<option value="' + data[i].ProductTypeNm + '">' + data[i].ProductTypeNm + '</option>');
            }
        }).fail(function (jqXHR, textStatus, errorThrown) {
            // Ajax fail callback function. 
            alert('Error getting product type!');
        });
    }

This is the HTML code:

    <table id="tblAppendGrid"></table>

[UPDATE]
I found out that my JSON is kinda different than how you load it in ctrlOptions:

    [{"ProductTypeNm":"BANK GUARANTEE"},{"ProductTypeNm":"CREDIT CARD"}, "ProductTypeNm":"FOREIGN EXCHANGE"}, {"ProductTypeNm":"INSTALLMENT LOAN"}, "ProductTypeNm":"KMK"},{"ProductTypeNm":"KREDIT EKSPOR"}, {"ProductTypeNm":"KREDIT INVESTASI"}, {"ProductTypeNm":"KREDIT LOKAL"}, {"ProductTypeNm":"LC"}, {"ProductTypeNm":"MONEY MARKET"}, {"ProductTypeNm":"NEGOSIASI/DISKONTO DENGAN KONDISI KHUSUS"}, {"ProductTypeNm":"OBL"}, {"ProductTypeNm":"OMNIBUS"}, {"ProductTypeNm":"SETTLEMENT"}, {"ProductTypeNm":"TIME LOAN"}, {"ProductTypeNm":"TRUST RECEIPT"}]

Is that the problem?

**Comment by hkalbertl** [comment]
Hi chandragie,

Similar to #69, I would like to ask a question first.
Is it a must to load options after add/insert row?
If no, you may:

1) Load the options in ASP.NET and embed as JSON in your view. Such as
```html
<script>
var myDropDownListOptions = @Html.Raw(Json.Encode(/*Put your array of options here!!*/));
$(function () {
  $('#tblAppendGrid').appendGrid({
    columns: [
      { name: 'ProductType', type: 'select', ctrlOptions: myDropDownListOptions }
    ]
  });
});
</script>
```

2) Make AJAX request for the options when document ready. Once the request finished, initialize `appendGrid` by using them is `ctrlOptions` (Line 22 of [drop down list demo](https://appendgrid.apphb.com/Demo/DropDownList))
```javascript
$(function () {
  $.ajax({
      /* Your AJAX call setting */
  }).done(function (options) {
    $('#tblAppendGrid').appendGrid({
      columns: [
        { name: 'ProductType', type: 'select', ctrlOptions: options }
      ]
    });
  });
});
```

Let me know if you still have questions. Thanks!

**Comment by hkalbertl** [comment]
If you really need to request for dynamic options after a row added / inserted, you may consider the following sample:

```javascript
$(function () {
  $('#tblAppendGrid').appendGrid({
    columns: [
      { name: 'ProductType', type: 'select', ctrlOptions: [] }
    ],
    afterRowAppended: function (caller, parentRowIndex, addedRowIndex) {
      getProductTypes(addedRowIndex);
    },
    afterRowInserted: function (caller, parentRowIndex, addedRowIndex) {
      getProductTypes(addedRowIndex);
    }
  });
});
function getProductTypes(rowIndex) {
  $.ajax({
    /* Your AJAX call setting */
    context: { targetRow: rowIndex } // Save the row index in context
  }).done(function (options) {
    var targetRowIndex = this.targetRow; // Get the row index from context
    var elem = $('#tblAppendGrid').appendGrid('getCellCtrl', 'ProductType', targetRowIndex);
    // Add options to select element
    for (var i = 0; i < options.length; i++) {
      $('<option></option>').text(options[i].ProductTypeNm).val(options[i].ProductTypeNm).appendTo(elem);
    }
  });
}
```
But please notice that if there are 100 rows in your grid then 100 requests will be sent. The user experience may not be good.

**Comment by chandragie** [comment]
Hi @hkalbertl ! Thank you so much for such detail answers. I really appreciate it and it helped a lot! Well, the fact is it is not a must to load after row added, since by the page loaded, I initiate the initRow:1, so I think I'm gonna use your first instruction. 
Currently I'm working on ASP.NET MVC application and using `appendGrid` so I think I will a little bit 'disturbing' you if you don't mind.
Here are some questions :
1. But you mentioned two points right there, are those supposed to be sequencial or do I need to choose one of those methods?
2. Back to my question about my JSON result, is it the right format for ctrlOptions in `appendGrid`?
3. Is using `$.ajax({.....})` different from `$.getJSON()` ?

**Comment by chandragie** [comment]
Hey @hkalbertl , did read my JSON result? I think the format is different than which you use to populate in dropdownlist. After being stressed because of that, I tried to do it manually, a little workaround though, but how do you think?

    $(function () {
        var productTypes = [];
        $.ajax({
            url: '/Pipeline/GetProductTypes',
            dataType: 'JSON',
            type: 'GET'
        }).done(function (options) {

First, I get each of the JSON value by the key

            var array = [];
            $.each(options, function (key, val) {

then I added it to an array variable:

            array.push(val.ProductTypeNm);
            });
            $('#tblAppendGrid').appendGrid({
                columns: [

Finally, I populated the dropdownlist via array.

            { name: 'ProductType', display: 'Product Type', type: 'select', ctrlOptions: array }
            ],
                initRows: 1
            });
        });
    });

Is this okay? Or there is another better soluton?

**Comment by hkalbertl** [comment]
Hi @chandragie,

1) The easiest way is try to modify the `options` returned from your request to any one of the supported format as showed in the [drop down list demo](https://appendgrid.apphb.com/Demo/DropDownList). Or re-format your `options` after request completed. For example:
```javascript
$.ajax({
  /* Your AJAX call setting */
}).done(function (options) {
  // Assume the format options is the same as what you said in your first post
  var newOptions = [];
  for (var i = 0; i < options.length; i++) {
    // Extract the product type and save in array
    newOptions.push(options[i].ProductTypeNm);
  }
  // Now, you can use the `newOptions` to initialize appendGrid
  $('#tblAppendGrid').appendGrid({
    columns:[
      {name : 'ProductType', display: 'Product Type', type:'select', ctrlOptions:options }
    ],
    initRows:1
  });
});
```

2) I guess the sample above may solve your Q2 already. May be you can take a look on the [documentation of ctrlOptions](https://appendgrid.apphb.com/Documentation#link-ctrlOptions) for more.

You are welcome to ask questions here :)
Hope it can help!

**Comment by chandragie** [comment]
Hey @hkalbertl , exactly like I did! Wow, you posted almost the same time as me.
Looking at your code, so that means my way is also correct right?

**Comment by hkalbertl** [comment]
Since there are several ways to create javascript array, your solution is fine :)

**Comment by chandragie** [comment]
Okay @hkalbertl !!
By the way, can we edit the display column into the `[DisplayName]` properties we set in the model class?

**Comment by hkalbertl** [comment]
I am not understand what you are asking. Are you talking about on the display name of each option? Such as "1" is the ID of "BANK GUARANTEE", so you want to display "BANK GUARANTEE" to user and keep "1" as the value of drop down list?

**Comment by chandragie** [comment]
No no, I'm talking about the display of each column in 
`columns:[
      {name : 'ProductType', display: '$somewords', type:'select', ctrlOptions: newOptions }
    ],`

I mean, can we alter the `$somewords` into the `[DisplayName]` properties we set in ASP.NET MVC model class ?
For example this one:

    public class ProductType
    {
        [DisplayName("Product Type")]
        public string ProductTypeNm { get; set; }
    }


Another question, can we use more than one format in populating dropdownlist? Let's say I want to use array and object. Is that possible?

**Comment by hkalbertl** [comment]
I see. I am not familiar with this. May be you can Google for a way that can extract this name and pass it as JSON.

Please check the `Array2` column in my [drop down list demo](https://appendgrid.apphb.com/Demo/DropDownList) for array of object example.

**Comment by chandragie** [comment]
Hi again @hkalbertl !

Thanks for your help recently. Right now I've been customizing the JSON loaded dropdownlist by adding cascade function on it to trigger populating other dropdownlist. And thanks to your tutorial, it works!

By the way, I have several questions here, hope you can help me again. Really appreciate it!

First, I was following your instruction to make `<textarea></textarea>` in [subPanelDemo](https://appendgrid.apphb.com/Demo/SubPanel). I found out that `appendGrid` does not have `<textarea></textarea>` type so that we need to use jQuery to build it. (Correct me if I'm wrong). Then I tried to customize the textarea by changing the `rows` value into 1 but it made no different. 

    $('<textarea></textarea>').css('vertical-align', 'middle').attr({
                id: 'tblAppendGrid_AdtComment_' + uniqueIndex,
                name: 'tblAppendGrid_AdtComment_' + uniqueIndex,
                rows: 1, cols: 60
            }).appendTo(cell);

Any suggestion to make it smaller?

Second, by using `appendGrid` to save data, do we have to always use the conventional way to do it? Judging from [serverHandlingDemo](https://appendgrid.apphb.com/Demo/ServerHandling), we just can save the data by that way. I'm thinking about using Entity Framework, can we?

Third, may be this one is out your scope to answer, but I know you are expert in this, so I ask you anyway :smile: 

    $('<input>', { type: 'text', maxLength: 1, id: ctrlId + '_Hour', name: ctrlId + '_Hour' }).css('width', '20px').appendTo(ctrl).spinner({ max: 9, min: 0 });

How to edit the `.css()` if we want to style more than one properties of the component?

**Comment by hkalbertl** [comment]
Good to know your implementation is working!

1. I guess the size of `textarea` is limited by web browser. You may set the width and height by using css method, such as `.css('height', 12)`. ([Reference](http://stackoverflow.com/questions/3896537/should-i-size-a-textarea-with-css-width-height-or-html-cols-rows-attributes))
2. My demo is one of the possible method to pass data back to server. You may develop in your own way :) I guess EF may not suitable for reading `appendGrid` data directly. But you can add some logic to convert submitted data (Request.Form) to EF models so it can do insert / update / delete for you.

**Comment by chandragie** [comment]
Hi @hkalbertl , well it is also because you guided me so good back then.

By the way, adding some logics to convert submitted data to EF? How do I do that? (newbie). One thing that I know if we couldn't use EF then we need to use conventional query building to insert the data (am I right?). I found some people using JSON to pass the submitted value back to the server, but I don't know yet if I could implement this on `appendGrid`.

And also, can we use the ASP.NET HTMLHelper if I want to bind the validation from the model, like in a normal form? For example, I want to make a textbox in one column, can I use: `textboxFor(m=>m.someProperties)` instead of using `{name:'someName', type:'text'}`?

**Comment by hkalbertl** [comment]
In order to submit data to server, you can use classic form post or [jQuery ajax](http://api.jquery.com/jquery.ajax/) method.

Refer to my [Server-side Handling](https://appendgrid.apphb.com/Demo/ServerHandling) demo, you may do something like that:
```java
List<Album> albums = new List<Album>();
string[] uniqueIndexes = Request.Form["tblAppendGrid_rowOrder"].Split(',');
for (int row = 0; row ‹ uniqueIndexes.Length; row++) {
  // Read the submitted values of albums from client side and convert it to EF model
  Album album = new Album();
  album.Name = Request.Form["tblAppendGrid_Name_" + uniqueIndexes[row]];
  album.Artist = Request.Form["tblAppendGrid_Artist_" + uniqueIndexes[row]];
  album.Year = int.Parse(Request.Form["tblAppendGrid_Year_" + uniqueIndexes[row]]); // You should validate the value is an integer before parsing it directly
  albums.Add(album);
}
// Save to database
using (var db = new AlbumContext()) {
  db.Albums.AddRange(albums); 
  db.SaveChanges(); 
}
```

For your second question, I believe the answer is no. You can do in that way. Here is a [demo](https://appendgrid.apphb.com/Demo/Validation) by using [jQuery Validation](http://bassistance.de/jquery-plugins/jquery-plugin-validation/) library which provide lots of options for different cases. Hope it can help!

**Comment by chandragie** [comment]
Hi again, today I'm facing some difficulties in using `appendGrid` or more precisely, jQuery that force me to ask you again @hkalbertl. So sorry to bother you :sob: 

First, my validation using your tutorial didn't work, I don't know why. But I got this error when `validate()` method called.

    TypeError: $.validator.methods[method] is undefined
    var result = $.validator.methods[method].call( this, element.value.replace(/\r/g...

Strangely, for the first time the page loaded (I'm using Firebug), there was no error written in the debugging console, but when I clicked a dropdownlist in the `appendGrid` suddenly the error code above listed in the console. I tried to google, but found nothing that I can do about it. Do you have any idea what's wrong? Here is my code:

    $(function () {
        $.ajax({
            url: '/Pipeline/GetProductTypes',
            dataType: 'JSON',
            type: 'GET'
        }).done(function (options) {
            var array = [];
            array.push('--Pilih--');
            $.each(options, function (key, val) {
                array.push(val.ProductTypeNm);
            });
            $('#tblAppendGrid').appendGrid({
                columns: [
            { name: 'ProductType', display: 'Tipe Produk', type: 'select', ctrlOptions: array, onChange: handleCascade, ctrlCss: { width: '150px' }, ctrlClass: 'ProductType' },
            { name: 'ProductSubType', display: 'Sub Tipe Produk', type: 'select', ctrlOptions: { '--Pilih--': '--Pilih--' }, ctrlAttr: { disabled: 'disabled' }, ctrlCss: { width: '150px'} },
            { name: 'Currency', display: 'MTU', type: 'select', ctrlOptions: { '': '--Pilih--', 'IDR': 'IDR', 'USD': 'USD' }, ctrlCss: { width: '80px'} },
            { name: 'Plafond', display: 'Plafond', type: 'text', ctrlCss: { 'width': '150px' }, ctrlClass: 'Plafond' },
            { name: 'Pricing', display: 'Pricing', type: 'text', ctrlCss: { 'width': '50px'} },
            { name: 'BNB', display: 'BNB', type: 'checkbox', ctrlProp: { checked: false} },
            { name: 'Commited', display: 'Commited', type: 'checkbox', ctrlProp: { checked: false} },
            { name: 'SigningPlan', display: 'Rencana Signing', type: 'ui-datepicker', ctrlAttr: { maxlength: 10 }, uiOption: { changeMonth: true, changeYear: true, showAnim: 'fold'} },
            { name: 'Keterangan', display: 'Keterangan', type: 'text', ctrlCss: { 'width': '200px'} }
            ],
                initRows: 1,

                hideButtons: {
                    removeLast: true,
                    moveUp: true,
                    moveDown: true,
                    insert: true
                },
                customGridButtons: {
                    remove: $('<button></button>').css('width', 'auto').text('Hapus').get(0),
                    append: $('<button></button>').text('Tambah').get(0)
                }
            });
        });

        $.validator.addClassRules('Plafond', {
            required: true,
            digits: true
        });
        $.validator.addClassRules('ProductType', {
            notFirstOption: "Pilih Tipe Produk"
        });

        $("#CreatePipeline").validate();
    });


Second, there's also an error in the datepicker component. As you see above, (I write it again below):

    { name: 'SigningPlan', display: 'Rencana Signing', type: 'ui-datepicker', ctrlAttr: { maxlength: 10 }, uiOption: { changeMonth: true, changeYear: true, showAnim: 'fold'} },

I did like your tutorial with adding some properties options. For the first time I picked a date, it works fine, but if I picked a date for the second time (or more) it will give me an error in the debugging console, well indeed the value in the datepicker changed. But if something's wrong listed in the console, we can't ignore it, right? Here is the error:

    SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
    return window.JSON.parse( data + "" );

And the last (for now), can we add some words at the footer? Let's say I want to add a string after the `add` button, can we?

So sorry if I bothered you so much recently, I really need your help in this since posting it in a single thread in `stackoverflow` usually takes long time to get an answer. I really appreciate your help!

**Comment by hkalbertl** [comment]
Hi,

1. It looks like you haven't define `notFirstOption`. You may take a look the [jQuery validation](http://jqueryvalidation.org/jQuery.validator.addMethod) documentation.
2. Would it be locale problem? (Such as the order of day-month-year or year-month-day) Also, are you donwloaded a copy of jQuery UI with animation effects?
3. There is no official way to do it but you can add text in this way
```javascript
$('<span></span>').text('Here is my footer message!!').addClass('some-classes-for-formatting').appendTo('#tblAppendGrid tfoot tr td');
```

For the first and second issues, You can create some dummy input outside of `appendGrid` to make sure they work normally first. Let me know if you still have problem on using `appendGrid`. Thanks!
