### ISSUE TITLE
To accept only numeric values.

### ISSUE THREAD

**Issue by yadusc1588** [hkalbertl/jquery.appendGrid#76]
Hi Albert,
          First of all I want to thank you for making such a great plugin. It really helps me a lot in making my project.
There is a question I would like to ask that how to restrict a text control to only accept numeric values OR to accept only text values?

**Comment by hkalbertl** [comment]
Hi yadusc1588,

There is no such native feature for `appendGrid`. But you can make use of some other plugins to constrain values entered by users. I can see there are lots of jQuery plugin provided mask input (such as [this one](http://digitalbush.com/projects/masked-input-plugin/)). You can generate the appendGrid normally and then create mask for the text / numeric controls as you required after row added / inserted event. For example,

```javascript
$('#tblAppendGrid').appendGrid({
  columns: [
    { name: 'TextOnly', type: 'text', display: 'Text only' },
    { name: 'NumericOnly', type: 'text', display: 'Numeric only' }
  ],
  afterRowAppended: initMaskControl,
  afterRowInserted: initMaskControl
});
function initMaskControl(caller, parentRowIndex, addedRowIndex){
  var textOnlyElem = $(caller).appendGrid('getCellCtrl', 'TextOnly', addedRowIndex);
  $(textOnlyElem).mask('aaaaa'); // Add the mask that fit your need!
  var numOnlyElem = $(caller).appendGrid('getCellCtrl', 'NumericOnly', addedRowIndex);
  $(numOnlyElem).mask('9999'); // Add the mask that fit your need!
}
```

If you don't want extra jQuery plugin, you may check this article for [native javascript keyboard restricting](http://www.aspsnippets.com/Articles/Restrict-user-from-entering-Special-Characters-in-TextBox-using-JavaScript.aspx).

Hope it can help. Thanks for using `appendGrid`!

**Comment by yadusc1588** [comment]
Thanks Albert for your response.
Though your suggestion was apt for the situation where a user is restricted to enter a fixed width numeric input like entering a mobile number or entering data for validations but in my case I don't want the width restriction. I want a text control to accept only numeric values (decimal values as well) irrespective of the width of numeric values.

**Comment by hkalbertl** [comment]
How about this one?
https://github.com/KevinSheedy/jquery.alphanum
