### ISSUE TITLE
maxBodyHeight is skewing column-heading width

### ISSUE THREAD

**Issue by mrsiva26** [hkalbertl/jquery.appendGrid#77]
When using maxBodyHeight (scrollbar), the width of column labels changes (from 157px to 154px) and last column (add row, delete row, move up, move down column) changes (from 91px to 85px). Any attempt to modify it's css from js or jquery doesn't help

**Comment by hkalbertl** [comment]
Hi mrsiva26,

Perhaps it is a bug on calculating columns width. I will check it and release an update shortly. Thanks!

**Comment by hkalbertl** [comment]
Hi again,

I would like to ask are you using bootstrap with `appendGrid`. If yes, can you help to download the pre-release version [here](https://github.com/hkalbertl/jquery.appendGrid/blob/master/jquery.appendGrid-development.js) and test it? Thanks

**Comment by hkalbertl** [comment]
Thanks for help! I will publish a new release soon.
Thanks for using `appendGrid`!
