### ISSUE TITLE
Do we have Row Level Events

### ISSUE THREAD

**Issue by MurthyPydikondala** [hkalbertl/jquery.appendGrid#78]
Thank you for making such a great plugin.
Is there any way we can catch the Row Level Events like onRowFocus  (OR) onRowClick.

I want to highlight the row where I am. I tried with JQuery. But It is not working on the Dynamically Created Columns.  Is there any way ?

**Comment by hkalbertl** [comment]
Hi, I guess jQuery provided such handler already. For example:

```javascript
$('#tblAppendGrid').appendGrid({ /* your initial parameters */ });
$('#tblAppendGrid').on('click', 'tbody tr', function () {
    // Get the table row DOM element
    var tr = this; 
    // Get the uniqueIndex based on the ID or table row
    var uniqueIndex = tr.id.substring(tr.id.lastIndexOf('_')+1);
    // Do anything that you want
});
```

Hope it can help. Thanks for using `appendGrid`!

**Comment by MurthyPydikondala** [comment]
Excellent. It is working. 
Thank you so much for your quick response and solution.
