### ISSUE TITLE
appendGrid ui-datepicker showing date picker ui only at second time hit on page from server but not at first time

### ISSUE THREAD

**Issue by RahulBisht1** [hkalbertl/jquery.appendGrid#79]
appendGrid ui-datepicker showing date picker ui only at second time hit on page from server but not at first time.
my code:->
obj.setType("ui-datepicker");
 Map<String,String> mapDateFormat = new HashMap<String, String>();
 mapDateFormat.put("dateFormat", "mm/dd/yy");
mapDateFormat.put("changeYear", "true" );
mapDateFormat.put("changeMonth", "true" );
obj.setUiOption(mapDateFormat);
Is order of js and css file in jsp is an issue?

**Comment by hkalbertl** [comment]
Hi RahulBisht1,

Sorry that I don't quite understand your question. It would be great to provide me a [jsfiddle](https://jsfiddle.net/) to show me your problem.

The order of JS and CSS may have some issue. You may download any of my sample in [demo section](https://appendgrid.apphb.com/Demo) for reference. Thanks!

**Comment by RahulBisht1** [comment]
Hi ,

My issue is that ui-datepicker ui is not getting render on datepicker field focus on first time appendGrid table redering but when table is populated at second time and then rendering of ui-datepicker is getting displayed on focus.
So please help me on this that ui-datepicker get render its ui of dtapicker on first time rendering of table. I am passing json data to populate columns and element at appendGrid table.

**Comment by hkalbertl** [comment]
I just tried appendGrid on different browser and it looks fine for me.
Have you tried my [UI datepicker demo](https://appendgrid.apphb.com/Demo/UiWidget)? Does it work for you?

If not, please tell me which browser (with version number) are you using and the coding for initial `appendGrid` which can show me your problem. Thanks!

**Comment by RahulBisht1** [comment]
Thanks for answering.
My code is as for json data to render columns->
jsp file head part->
 <link href="jscript/jquery.appendGrid-1.6.2.css" rel="stylesheet" />
<script type="text/javascript" src="jscript/jquery.appendGrid-1.6.2.js"></script>
<script type="text/javascript" src="jscript/jquery.appendGrid-development.js"></script> 
My javascript function which render the table of appenGrid->
function loadgrid(id,json)
{
	$("#"+id).appendGrid({
    caption: '    ',
    initRows: 1,
    columns: json,
//	initData: renderList,
    afterRowRemoved: function (caller, rowIndex) {
           var rowOrder = $(caller).appendGrid('getRowOrder');
		   var tableID = $(caller).attr("id");
		   var rowIndexFieldName = "rowIndex_"+tableID;
		   for(var i=0;i<rowOrder.length;i++)
							{
							   var rowIndex = $(caller).appendGrid('getRowIndex', rowOrder[i]);
							   $(caller).appendGrid('setCtrlValue', $("#"+rowIndexFieldName).val(), rowIndex, i+1);
							}
        },
    afterRowInserted: function (caller, parentRowIndex, addedRowIndex) {
            				var rowOrder = $(caller).appendGrid('getRowOrder');
							var tableID = $(caller).attr("id");
							var rowIndexFieldName = "rowIndex_"+tableID;
							for(var i=0;i<rowOrder.length;i++)
							{
							var rowIndex = $(caller).appendGrid('getRowIndex', rowOrder[i]);
							$(caller).appendGrid('setCtrlValue', $("#"+rowIndexFieldName).val(), rowIndex, i+1);
							}
                         },
               afterRowAppended: function (caller, parentRowIndex, addedRowIndex) {
                         
                           var rowOrder = $(caller).appendGrid('getRowOrder');
						   var tableID = $(caller).attr("id");
							var rowIndexFieldName = "rowIndex_"+tableID;
							for(var i=0;i<rowOrder.length;i++)
							{
						var rowIndex = $(caller).appendGrid('getRowIndex', rowOrder[i]);
							   $(caller).appendGrid('setCtrlValue', $("#"+rowIndexFieldName).val(), rowIndex, i+1);
							}
                        },
  
	maxBodyHeight: 130, // Limit the table body height to 240px
    maintainScroll: true ,
	// Scroll the table body when new rows are appended
	customRowButtons: [
              { uiButton: 
			  { icons: { primary: 'ui-icon-copy' }, text: false }, //for copying the data of row
			  click: function (evtObj, uniqueIndex, rowData) {
			   $("#"+id).appendGrid('appendRow', [
       rowData
    ]);
			  }, btnAttr: { title: 'Copy Row!' }, atTheFront: true }
        ],
		
      //extended business rules changes
        customFooterButtons: [
                              { uiButton: { icons: { primary: 'ui-icon-check' }, text: false }, 
                  			btnAttr: { title: 'Validation' }, 
                  			click: function (evt) {
                  			//alert(("#"+id).appendGrid('getRowCount'));
                  			getRowNumber(id);
                  				var formData = new FormData(document.getElementById("ruleDetailForm"));
                  				
                  				$
                  						.ajax({
                  							type : "POST",
                  							url : "validateMDMForm1.action",
                  							data : formData,
                  							async : false,
                  							processData : false,
                  							contentType : false,
                  							success : function(response) {
                  								//alert(response);
                  								 $.each(response, function(key, val){
                  								      /* alert(key);
                  								      alert(val); */
                  									  if(val!='Y'){
                  									  var str = key.substring(0, key.length-3);
                  									 /*  alert(str); */
                  									  document.getElementById(str).value=val;
                  									  } 
                  									  else{
                  										  var str = key.substring(0, key.length-3);
                  										  $("#"+str).addClass("validate[required]");
                  										  $("#"+str).css("background","red");
                  									  }
                  								      });
                  							}
                  						
                  						});
                  				
                  				var a=id+"_validation";
								//alert(document.getElementById(a).value);
								document.getElementById(a).value="true";
								//alert(document.getElementById(a).value);
                  				}, 
                  	
                  			atTheFront: true },
                                                    
                                            ],
                  		 hideRowNumColumn: true,
                          rowButtonsInFront: true,
                          hideButtons: {
                          moveUp: true,
                          moveDown: true,
                          insert: true
                  		
                      }
					  
                  	
                  	
                  });
	
	 $("#"+id).append('<input type="hidden" name="field_name" id="'+id+'_validation" value="false" /> ');
		//extended business rules changess
	
}

Now please tell how to show ui-datepicker on focus of field on first call of above method. As now it showing at second time but not at first time.?

**Comment by hkalbertl** [comment]
Hi,

I cannot see any problems in your given sample code. But for the definition in head section, it looks like you included appendGrid js file for two times, ie jquery.appendGrid-1.6.2.js and jquery.appendGrid-development.js. The development.js is used for me (and may be other developers) for new features. It may causes unexpected behavior after initialized the grid.

If the problem is still there after you removed the development.js, I would like to know what is your column definition for that datepicker. I am not sure are there any parameters which is/are not valid in your case. 

May be you can simply test it by removing all ui-datepicker parameters and see does it work as you expected. And try to add parameters one by one. For example:

First, create a basic datepicker
```javascript
{
  columns:[
    { name: 'Date', type: 'ui-datepicker' }
  ]
}
```

Second, add a one more parameter and test if it still working fine
```javascript
{
  columns:[
    { name: 'Date', type: 'ui-datepicker', uiOption: { dateFormat: 'yy/mm/dd'}  }
  ]
}
```

After that, put one more parameter for testing
```javascript
{
  columns:[
    { name: 'Date', type: 'ui-datepicker', uiOption: { dateFormat: 'yy/mm/dd', showMonthAfterYear: true }  }
  ]
}
```
