### ISSUE TITLE
Disable editing of certain columns

### ISSUE THREAD

**Issue by beerygaz** [hkalbertl/jquery.appendGrid#81]
Is it possible to disable the ability to edit certain columns without hiding them?  So the user could see the table but only edit columns in the row?  

e.g.:

columns: [ 
{name: 'Name', type: 'text', enabled: false}.
{name: 'Age', type: 'text', enabled: true}
]

**Comment by hkalbertl** [comment]
Hello, I am still having easter holiday break so the response may be a bit slow.

Perhaps you can define a CSS class for target column(s). And then enable / disable them by using:

```javascript
$('#tblAppendGrid .my-target-input').prop('disabled', true);
```

Hope it can help :)
