### ISSUE TITLE
Navigating/Scrolling through controls(like text boxes) using down/up/left/right keys

### ISSUE THREAD

**Issue by yadusc1588** [hkalbertl/jquery.appendGrid#82]
Hi,
      while using appendgrid I  noticed that you can't select/scroll through the controls(like text boxes etc) by using Up/ Down/ Left/ Right arrow keys. To visit each control you need to use Tab button instead.
Is there any way to navigate through controls using navigational keys and if not how about getting this feature in the future releases.

**Comment by hkalbertl** [comment]
Hi yadusc1588,

Do you mean you cannot select text in text box by using shift + arrow keys?
`appendGrid` will not restrict this action. Can you try it on different web browser?

If I misunderstood your question, can you give a sample (such as jsfiddle) for me? Thanks!

**Comment by yadusc1588** [comment]
Hi ,
Suppose you don't have any mouse attached to your computer and you only have keyboards. Right now in plugin if you want to write something in a particular text box you have to press "Tab"  button to go to that text box control . Pressing the up/down/left/right key does not have any affect.
Thus I want to ask you can this feature be added as an **"Enhancement" ** in the plugin in future releases?

**Comment by hkalbertl** [comment]
Hi again,

I know what you mean now. But perhaps it is not good to create a standard feature on it as we can create some custom type or non editable input.

In your case, I guess all the columns are textbox. So, please reference to my [example](https://jsfiddle.net/hkalbertl/at6xnr18/) that may help. I just implemented Up and Left arrow and I guess you can complete the Down and Right arrow :)

Thanks!

**Comment by yadusc1588** [comment]
Thanks for the help Albert.
Its working.  :+1:
