### ISSUE TITLE
in appengGrid table i have 35 columns with 20 rows but it is two horizontal scrollbars and desired is one 

### ISSUE THREAD

**Issue by RahulBisht1** [hkalbertl/jquery.appendGrid#83]
Hi,

I am using appendGrid table. 
And in appengGrid table i have 35 columns with 20 rows but it is two horizontal scrollbars and desired is one . One horizontal scrollbar is of div containing appendGrid table and other horizontal scroll bar if appendGrid table itself. And our requirement is to have only one horizontal scroll bar.
Sample code is:-
<div style="overflow-x:scroll;overflow-y:hidden;max-height:290px;max-width:1300px;"><table id="relationalTableID_" style="overflow-x:hidden;max-width:1250px;"></table></div>
//now appebdGrid code
$('#tblAppendGrid').appendGrid({.....//so on

Please help to have only one horizontal scrollbar and one vertical scrollbar

**Comment by hkalbertl** [comment]
Hi,

`appendGrid` should not generate horizontal scrollbar on table normally. May be you can add a class to focus your browser to hide it. For example:

```css
#tblAppendGrid table, #tblAppendGrid tbody {
  overflow-x: hidden;
}
```
