### ISSUE TITLE
Append Grid blank buttons when used on joomla website

### ISSUE THREAD

**Issue by matthewenger** [hkalbertl/jquery.appendGrid#86]
Hello,

I am trying to use appendgrid inside a joomla plugin we wrote but the buttons are blank (no images).

![Image untitled-1](https://cloud.githubusercontent.com/assets/17839615/15606268/7ab6cdce-244e-11e6-9001-ec0fb0a7bc60.jpg)

Any ideas? There are no errors in Firefox console.

**Comment by hkalbertl** [comment]
Hi matthewenger,

I guess joomla is using bootstrap. So it would be the same problem as #54.
You may check my [Bootstrap demo](https://appendgrid.apphb.com/Demo/Bootstrap) and try to modify the order of `<script></script>` tags to workaround this problem.

Hope it can help :)

**Comment by matthewenger** [comment]
Thanks, that helped alot.

Basically i added the following command before calling appendgrid:
var btn = $.fn.button.noConflict();

**Comment by hkalbertl** [comment]
Hi again,

May be you have specified the above code in a wrong place.
Please check this example:

```html
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8" />
	<title>Bootstrap</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
	<link rel="stylesheet" href="https://code.jquery.com/ui/1.11.4/themes/black-tie/jquery-ui.css" />
	<!--1. jQuery-->
	<script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
	<!--2. Bootstrap-->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
	<!--3. Set no conflict on Bootstrap button and redirect it to bsButton-->
	<script>
		var _bsbtn = $.fn.button.noConflict();
		$.fn.bsButton = _bsbtn; // So, you can use the BS button by $(...).bsButton(...);
	</script>
	<!--4. Include the jQuery UI-->
	<script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
	<script>
		// Create a jQuery UI button to test
		$(function(){
			$('#jquery-ui-button').text('jQuery UI Button').button({
				icons: {
					primary: 'ui-icon-locked'
				}
			});
		});
	</script>
</head>
<body>
	<form action="">
		<button type="button" id="jquery-ui-button"></button>
		<button type="button" id="bootstrap-ui-button" class="btn btn-default">Bootstrap Button</button>
	</form>
</body>
</html>
```
If the script order is not correct, you will not able to get a working jQuery button even `appendGrid` is not included. You may modify my example and put it in your website :)
