### ISSUE TITLE
Appendgrid browser compatibility issue with Firefox  

### ISSUE THREAD

**Issue by sarjerav** [hkalbertl/jquery.appendGrid#88]
Hello 

I have implemented the **append grid** into my project but there is problem with browser Like Firefox.

There won't be any problem with Chrome with **long text** but problem is with only **Firefox Browser**.

![appendgrid_firefox_issue](https://cloud.githubusercontent.com/assets/3907661/15961607/4212e4d2-2f23-11e6-896e-28a18be59c52.JPG)

Awaiting for your reply eagerly.

Thanks
sarje

**Comment by hkalbertl** [comment]
Hello and sorry for late reply. `appendGrid` should work fine on modern browsers. Can you give me the sample code (jsfiddle / download link / reply here) to initialize your grid for reference? Thanks!
