### ISSUE TITLE
Is jquery.appendGrid is free to use and free to modify ?

### ISSUE THREAD

**Issue by abhinavsharma1** [hkalbertl/jquery.appendGrid#89]
I want to use jquery.appendGird in my project.I am little confuse with respect to its License and terms.
Thus want some clarification on below points.
1. Is it is free to use/charges ? 
2. If i want to alter its design or change it Logic as per my requirement .Is this cause any disagreement of License terms or any other issue ?
3.Any cost in future.
4. Is it free to use in commercial /Client Projects ?

Please kindly replay on theses.
Thanks

**Comment by hkalbertl** [comment]
Hi abhinavsharma1,

For the answer of question 1, 2 and 4. `appendGrid` is free to use / modify in commercial projects under 
[MIT License](https://opensource.org/licenses/mit-license.php). It is good enough if you can put a line in your "about" dialog that said your software used `appendGrid`. I found this [website](http://www.tawesoft.co.uk/kb/article/mit-license-faq) about MIT License that may help you.

For question 3. I would say no in the foreseeable future.

Hope it can help :-)

**Comment by abhinavsharma1** [comment]
Thanks for updates.
