### ISSUE TITLE
How to disable controls from serverside. add delete button

### ISSUE THREAD

**Issue by sachin0606** [hkalbertl/jquery.appendGrid#91]
Hi, 
i integrated this tool in one of my project where i want to disable the controls based on role. can you suggest how can we apply this? 

as i saw we can hide column but not controls column. 

else have to loop through rows and get control and disable the buttons??

Thanks for the tool.

**Comment by hkalbertl** [comment]
Hi sachin0606,

May be you can modify the [hideButtons](https://appendgrid.apphb.com/Documentation#link-hideButtons) option based on users' role before initial the grid. For example:

```javascript
$(function() {
    $('#tblAppendGrid').appendGrid({
        columns: [/* Your columns*/],
        hideButtons: {
            // Remove all buttons at the end of rows
            insert: true,
            remove: true,
            moveUp: true,
            moveDown: true
        }
    });
});
```

Hope it can help. Thanks for using `appendGrid`!

**Comment by sachin0606** [comment]
Cant we call seperate function for this do ? now while initialising the grid???

**Comment by hkalbertl** [comment]
Sorry that it is not supported by `appendGrid`.
The control buttons are generated during initialize stage.


But I guess you can initial grid with all buttons and show / hide the buttons by calling the following function:

```javascript
function toggleGridButtons(showIt){
  if (showIt) {
    // Row level buttons
    $('#tblAppendGrid button.insert,#tblAppendGrid button.remove,#tblAppendGrid button.moveUp,#tblAppendGrid button.moveDown').show();
    // Buttons at footer row
    $('#tblAppendGrid button.append,#tblAppendGrid button.removeLast').show();
  } else {
    // Row level buttons
    $('#tblAppendGrid button.insert,#tblAppendGrid button.remove,#tblAppendGrid button.moveUp,#tblAppendGrid button.moveDown').hide();
    // Buttons at footer row
    $('#tblAppendGrid button.append,#tblAppendGrid button.removeLast').hide();
  }
}
```

**Comment by sachin0606** [comment]
Thanks! this is what i expecting...
