### ISSUE TITLE
AppendGrid to JSON

### ISSUE THREAD

**Issue by andersonls** [hkalbertl/jquery.appendGrid#92]
Hello,

is there a function to transform all rows into a Json scructure? For example:

```javascript
$('#tblAppendGrid').appendGrid({
        initRows: 0,
        columns: [
            { name: 'pct_qtd', display: 'Qtd', type: 'text', ctrlAttr: { readonly: true, required: true }, ctrlCss: { width: '80px'} },
            { name: 'pct_obs', display: 'Obs', type: 'text', ctrlAttr: { readonly: true, required: true }, ctrlCss: { width: '80px'} },
        ],
});

var data = {'pct_qtd': 1, 'pct_obs': 'abc'};
$('#tblAppendGrid').appendGrid('appendRow', [data]);
var data = {'pct_qtd': 10, 'pct_obs': 'cdf'};
$('#tblAppendGrid').appendGrid('appendRow', [data]);
```
I want a function to return the JSON, so i can save and restore the table's data using the browser's localStorage.

```javascript
[
    {"pct_qtd":1, "pct_obs":"abc"},
    {"pct_qtd":10, "pct_obs":"cdf"},
]
```

**Comment by hkalbertl** [comment]
Hi andersonls,

Have you tried [getAllValue](https://appendgrid.apphb.com/Documentation#link-getAllValue)? It will return the grid data in array format that I believe is what you wanted.

Hope it can help. Thanks for using `appendGrid`!

**Comment by andersonls** [comment]
Hi @hkalbertl, yes i ended up using [getAllValue](https://appendgrid.apphb.com/Documentation#link-getAllValue) with JSON stringify

```javascript
var data = $('#tblAppendGrid').appendGrid('getAllValue');
var jsonData = JSON.stringify(data);
```
And to restore
```javascript
var data = JSON.parse(jsonData);
$('#tblAppendGrid').appendGrid('appendRow', data);
```

**Comment by hkalbertl** [comment]
Good to know :)

**Comment by andersonls** [comment]
One more question, does this work with subgrids?

One of my tables has a subgrid and the above code is not working (the subgrid is not being populated). Do i need to write a wrapper for the appendRow to populate the subgrid?

The getAllValue returns something like:

```javascript
[{"id":"1059","box_name":"P","weight":"1","ped_serial_0":1}]
```
I also tried implementing the subPanelGetter to return the array in the same format as passed to the initData of the [SubGrid demo](https://appendgrid.apphb.com/Demo/SubGrid):

```javascript
[{"id":"1059","boxName":"P","weight":"1","SubGridData":[{"ped_serial":1}]}]
```

**Comment by hkalbertl** [comment]
Hi,

If you initialize the grid based on my [SubGrid](https://appendgrid.apphb.com/Demo/SubGrid) example, probably sub-grid data in "object mode" is generated.

I guess you can modify your `subPanelGetter` function as follow:

```javascript
{
  subPanelGetter: function (uniqueIndex) {
    return {
      // Get sub-grid data in "array mode" and save it to the property named `SubGridData` that matched to `rowDataLoaded`
      SubGridData: $('#tblSubGrid_' + uniqueIndex).appendGrid('getAllValue')
    };
  }
}
```

The `getAllValue` should generate data exactly the same as the one in your `initData`.
If not, please show me your code and sample data for checking :)

**Comment by andersonls** [comment]
Ok, now it's working. I forgot to add the rowDataLoaded method.

It still doesn't work with the appendRow method, but i can work with the initData instead. I only need this once when the page is loaded.

**Comment by hkalbertl** [comment]
Not bad! Good luck in your project!
