### ISSUE TITLE
Can we make the same grip with verticle options?

### ISSUE THREAD

**Issue by sachin0606** [hkalbertl/jquery.appendGrid#93]
hI, 

Can we make the grid like below

<tr>
<td>
Lable
</td>
<td>
control (Like check box, textbox,etc )
</td>
</tr>

as i using it in one of my application for educational Qualification like below:

Qualification Type:
Qualification Area
Specialization:
Grade:
University:
Attended Year
Completed Year

so on.. 

its not an issue. 
 just question to implement same thing in row format not column format?? 

thanks.

**Comment by hkalbertl** [comment]
Hi sachin0606,

It should be the same question as #50.
I guess it is a bit hard to achieve this.
Possibly it required to rewrite the core and it may cause other issues...

**Comment by sachin0606** [comment]
Yes, i may help you in this. but i am basically .net not from java script.. but your comments in code made me to understand the logic.  anyway let me know if you gonna work on this. and as i understood it may only need to change the logic in method -> 

 function insertRow(tbWhole, numOfRowOrRowArray, rowIndex, callerUniqueIndex) {
}

**Comment by hkalbertl** [comment]
It is great to know that you want to help `appendGrid`!
But I believe it is not that simple to just modify the "insertRow" function.

You may need to consider the following area:
- There is no "insertColumn" function in javascript. So, you are required to rewrite the logic for generating table.
- There is no table header / body / footer in vertical mode. You are required to calculate the insert column index for all row operations(such as insert / append / move up / etc).
- The CSS style are designed for "horizontal" mode. You are required to build another set of style for "vertical" mode.
- Required to support all existing options / methods (if possible). Such as fixed header / sub-panel.
- (May be more...)

Again, you can modify my code to fit your need.
So, you may just omit / ignore issues above.

I am afraid it is too hard to standardize it to a general option for this library...
