### ISSUE TITLE
Hide a particular row in appendgrid

### ISSUE THREAD

**Issue by siddhant749** [hkalbertl/jquery.appendGrid#94]
Hi,
A query,
The build in-code supports hiding of a particular column ,is there a way to hide a row say row number 2 by passing row number??
Also is there a way to get display name of columns ( not the actual name)??

**Comment by hkalbertl** [comment]
Hi siddhant749,

I tried to implement this feature previously but got some issues on calculate the row number (first column) and it may break 3rd party validation plugin when the rows are hidden.

If you really want to do so, you can try the following code:

```javascript
function showHideGridRow(uniqueIndex, visible) {
  // Please change the following `tblAppendGrid` if you are using another table ID
  if (visible) {
    $('#tblAppendGrid_Row_' + uniqueIndex).show();
  } else {
    $('#tblAppendGrid_Row_' + uniqueIndex).hide();
  }
}
```

Hope it can help :)
