### ISSUE TITLE
cascading dropdown binding while loading  grid

### ISSUE THREAD

**Issue by sachin0606** [hkalbertl/jquery.appendGrid#95]
Hi hkalbertl, 

had 3 dropdowns which are cascading. i dont have proble to generate but getting issue while loading. how to load dropdownlist which are cascading.

ex:
qulaification type : main dropdown

Qualification Area : second dropdown

Specialization : third. 

while binding need to call onselected index change event , but how to call and load?

**Comment by hkalbertl** [comment]
Hi sachin0606,

If your drop down list do not required remote data, please check [this example](https://appendgrid.apphb.com/Demo/DropDownList).
If not, you are required to modify the `onChange` event of drop down to make AJAX request once the option changed. For example:

```javascript
$('#tblAppendGrid').appendGrid({
  ...
  columns: [
    ...
    {
      name: 'QulaificationType', ...
      onChange: function (evt, rowIndex) {
        // Load the list of option
        $.ajax( /* Your request settings */ ).done(function (result) {
          // Find the second drop down
          var qualificationAreaElem = $('#tblAppendGrid').appendGrid('getCellCtrl', 'QualificationArea', rowIndex);
          // Build your options
          for (var i = 0; i < result.length; i++) {
            qualificationAreaElem .options[i] = ...
          }
        });
      }
    },
    { name: 'QualificationArea', ... },
    { name: 'Specialization', ... },
    ...
  ]
  ...
});
```
