### ISSUE TITLE
I want use json give appendgrid populate the data ,how do???? please help me

### ISSUE THREAD

**Issue by ObjectXhy** [hkalbertl/jquery.appendGrid#97]
this i do but no success : 
  var key = GetQuery('key').val();
                getAjax("../Order/OrderCarDetail.ashx", "action=BindCarTable&key="+ key, function (data) {
                   var  jsonData = eval("(" + data + ")");                
                   $.each(jsonData, function (i) {
                       $('#tblAppendGrid').appendGrid('appendRow', jsonData[i]);
                   });
                })

**Comment by hkalbertl** [comment]
Hi ObjectXhy,

Sorry that I was out of town last week so I hope it is not too late to reply your question.

I afraid your code `var jsonData = eval("(" + data + ")");` will cause parse error. Please make sure it will produce JSON data with [correct syntax](http://www.w3schools.com/js/js_json_intro.asp).

When your `jsonData` variable contain array data with correct format, `appendGrid` should able to append rows with data. By the way, you can pass the `jsonData` array data to `appendRow` method directly so no need to call `$.each`. Please check the [documentation](https://appendgrid.apphb.com/Documentation#link-appendRow) for more.

For example:

```javascript
var jsonData = eval("(" + data + ")"); // Please fix it
$('#tblAppendGrid').appendGrid('appendRow', jsonData); // Pass the array of data to appendRow
```
